/**
 * DPDP Compliance Rules for PDF Report Generation
 * Digital Personal Data Protection Act 2023 & DPDP Rules 2025
 */

export interface DPDPComplianceRule {
  questionId: string;
  category: string;
  requirement: string;
  governmentRef: string;
  officialLink: string;
  deadline: string;
  penalty: string;
  actionIfNonCompliant: string[];
  actionIfCompliant: string;
}

export const DPDP_COMPLIANCE_RULES: Record<string, DPDPComplianceRule> = {
  // DATA INVENTORY & MAPPING
  inventory_1: {
    questionId: 'inventory_1',
    category: 'Data Inventory & Mapping',
    requirement: 'Personal Data Identification and Documentation',
    governmentRef: 'DPDP Act 2023 - Section 2(t) | DPDP Rules 2025 - Rule 3',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 50 Cr for processing without lawful basis',
    actionIfNonCompliant: [
      'Conduct comprehensive data discovery across all systems and databases',
      'Create personal data inventory categorising: names, emails, phones, Aadhaar, PAN, IP addresses, location, biometrics',
      'Document data sources: web forms, mobile apps, third-party integrations, offline collection',
      'Tag data by sensitivity level (general, sensitive, children)',
      'Implement automated data classification tools for ongoing discovery',
    ],
    actionIfCompliant: 'Maintain quarterly data inventory reviews. Update inventory when new data collection points are added.',
  },
  inventory_2: {
    questionId: 'inventory_2',
    category: 'Data Inventory & Mapping',
    requirement: 'Records of Processing Activities (ROPA)',
    governmentRef: 'DPDP Act 2023 - Section 8(7) | DPDP Rules 2025 - Rule 3',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 50 Cr for inadequate documentation',
    actionIfNonCompliant: [
      'Create ROPA template with mandatory fields: processing purpose, data categories, retention periods',
      'Document legal basis for each processing activity (consent, contract, legal obligation)',
      'Record all third parties receiving personal data with their purposes',
      'Include security measures applied to each data category',
      'Designate ROPA owner and establish quarterly review process',
    ],
    actionIfCompliant: 'ROPA maintained. Ensure annual review and update upon any new processing activity.',
  },
  inventory_3: {
    questionId: 'inventory_3',
    category: 'Data Inventory & Mapping',
    requirement: 'Data Flow Mapping',
    governmentRef: 'DPDP Act 2023 - Section 8 | Best Practice',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Indirect - Required for compliance demonstration',
    actionIfNonCompliant: [
      'Map data flows from collection to deletion for each data category',
      'Identify all touchpoints: front-end apps, APIs, databases, backups, analytics',
      'Document cross-border data flows with destination countries',
      'Identify third-party processors and sub-processors in each flow',
      'Create visual data flow diagrams for key processes',
    ],
    actionIfCompliant: 'Data flows documented. Update flows when architecture changes.',
  },
  inventory_4: {
    questionId: 'inventory_4',
    category: 'Data Inventory & Mapping',
    requirement: 'Data Retention Schedule',
    governmentRef: 'DPDP Act 2023 - Section 8(5) | DPDP Rules 2025 - Rule 4',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 50 Cr for retaining data beyond necessary period',
    actionIfNonCompliant: [
      'Define retention periods for each data category aligned with legal requirements',
      'Consider: consent validity, contract duration, statutory obligations (7 years for financial)',
      'Implement automated deletion triggers when retention period expires',
      'Create exception process for legal holds and dispute resolution',
      'Document retention justification for each category in ROPA',
    ],
    actionIfCompliant: 'Retention schedules defined. Implement automated purging and periodic compliance audits.',
  },

  // CONSENT MANAGEMENT
  consent_1: {
    questionId: 'consent_1',
    category: 'Consent Management',
    requirement: 'Granular and Purpose-Specific Consent',
    governmentRef: 'DPDP Act 2023 - Section 6(1), 6(3) | DPDP Rules 2025 - Rule 3(1)',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 50 Cr per violation',
    actionIfNonCompliant: [
      'Replace bundled consent checkboxes with separate consent for each purpose',
      'Pre-ticked boxes are INVALID - implement unchecked default states',
      'Separate consent required for: service delivery, marketing, analytics, profiling',
      'Implement consent versioning to track which version user agreed to',
      'Create consent preference centre allowing granular control',
    ],
    actionIfCompliant: 'Granular consent implemented. Conduct annual consent UX audit for dark patterns.',
  },
  consent_2: {
    questionId: 'consent_2',
    category: 'Consent Management',
    requirement: 'Easy Consent Withdrawal (Withdrawal Parity)',
    governmentRef: 'DPDP Act 2023 - Section 6(4) | DPDP Rules 2025 - Rule 3(3)',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 50 Cr for making withdrawal difficult',
    actionIfNonCompliant: [
      'Implement one-click consent withdrawal matching consent mechanism',
      'Create self-service consent management portal accessible from user account',
      'Do NOT require: login, multiple steps, email verification, or phone calls for withdrawal',
      'Process withdrawal within 24 hours and send confirmation',
      'Stop processing immediately upon withdrawal (except legal obligations)',
    ],
    actionIfCompliant: 'Withdrawal parity achieved. Monitor withdrawal completion times monthly.',
  },
  consent_3: {
    questionId: 'consent_3',
    category: 'Consent Management',
    requirement: 'Multilingual Consent Notices',
    governmentRef: 'DPDP Act 2023 - Section 5(1) | DPDP Rules 2025 - Rule 3',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 50 Cr for non-compliant notices',
    actionIfNonCompliant: [
      'Provide notices in Hindi and English at minimum',
      'Add regional languages based on user demographics (22 scheduled languages)',
      'Implement language detection and automatic locale selection',
      'Ensure translations are legally accurate, not just machine-translated',
      'Test notices with native speakers for clarity',
    ],
    actionIfCompliant: 'Multilingual notices available. Review translations when notices change.',
  },
  consent_4: {
    questionId: 'consent_4',
    category: 'Consent Management',
    requirement: 'Consent Record Keeping',
    governmentRef: 'DPDP Act 2023 - Section 6 | DPDP Rules 2025 - Rule 3',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Unable to demonstrate lawful processing - Up to Rs. 250 Cr',
    actionIfNonCompliant: [
      'Implement consent logging with: timestamp, IP address, user agent, consent version',
      'Store consent records for minimum 7 years (recommended)',
      'Enable audit trail retrieval by user ID or date range',
      'Include proof of what user was shown at time of consent',
      'Implement tamper-proof consent storage (blockchain optional)',
    ],
    actionIfCompliant: 'Consent logs maintained. Ensure log backup and disaster recovery.',
  },

  // PRIVACY NOTICES
  notices_1: {
    questionId: 'notices_1',
    category: 'Privacy Notices',
    requirement: 'Standalone Pre-Collection Privacy Notice',
    governmentRef: 'DPDP Act 2023 - Section 5 | DPDP Rules 2025 - Rule 3',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 50 Cr for collecting data without proper notice',
    actionIfNonCompliant: [
      'Create standalone privacy notice separate from Terms of Service',
      'Display notice BEFORE or AT the time of data collection',
      'Ensure notice is not buried in long documents - use layered approach',
      'Include prominent link in all data collection forms',
      'Mobile apps: Display notice before permissions are requested',
    ],
    actionIfCompliant: 'Pre-collection notices in place. Review notice placement during UX updates.',
  },
  notices_2: {
    questionId: 'notices_2',
    category: 'Privacy Notices',
    requirement: 'Notice Content Requirements',
    governmentRef: 'DPDP Act 2023 - Section 5(1) | DPDP Rules 2025 - Rule 3',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 50 Cr for inadequate notice',
    actionIfNonCompliant: [
      'Include in notice: personal data categories collected, processing purposes',
      'Add: third-party sharing details, retention periods, data principal rights',
      'Provide DPO/Grievance Officer contact with email and address',
      'Use plain language - avoid legalese and technical jargon',
      'Include how to lodge complaint with Data Protection Board',
    ],
    actionIfCompliant: 'Notice content compliant. Review annually for accuracy.',
  },
  notices_3: {
    questionId: 'notices_3',
    category: 'Privacy Notices',
    requirement: 'Notice Update and Re-notification',
    governmentRef: 'DPDP Act 2023 - Section 5, 6 | DPDP Rules 2025',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Processing without valid notice - Up to Rs. 50 Cr',
    actionIfNonCompliant: [
      'Implement notice version control with change tracking',
      'Notify users of material changes via email and in-app notification',
      'Re-obtain consent when adding new processing purposes',
      'Maintain archive of all previous notice versions with dates',
      'Give users 30-day notice period before changes take effect',
    ],
    actionIfCompliant: 'Update process documented. Trigger re-notification when privacy practices change.',
  },

  // DATA PRINCIPAL RIGHTS
  rights_1: {
    questionId: 'rights_1',
    category: 'Data Principal Rights',
    requirement: 'Right to Access (Data Subject Access Request)',
    governmentRef: 'DPDP Act 2023 - Section 11 | DPDP Rules 2025 - Rule 5',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 200 Cr for failing to respond to requests',
    actionIfNonCompliant: [
      'Build DSAR portal for users to submit access requests',
      'Implement identity verification for requesters',
      'Create 90-day SLA tracking with escalation procedures',
      'Provide: data summary, processing purposes, third-party disclosures',
      'Enable data export in machine-readable format (JSON, CSV)',
    ],
    actionIfCompliant: 'DSAR process operational. Monitor response times and completion rates.',
  },
  rights_2: {
    questionId: 'rights_2',
    category: 'Data Principal Rights',
    requirement: 'Right to Correction',
    governmentRef: 'DPDP Act 2023 - Section 12 | DPDP Rules 2025 - Rule 5',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 200 Cr for failing to correct inaccurate data',
    actionIfNonCompliant: [
      'Provide self-service profile editing for basic fields',
      'Create correction request workflow for restricted fields',
      'Maintain audit trail of all corrections with timestamps',
      'Propagate corrections to all systems including backups',
      'Notify third parties who received incorrect data',
    ],
    actionIfCompliant: 'Correction process available. Ensure correction propagation to downstream systems.',
  },
  rights_3: {
    questionId: 'rights_3',
    category: 'Data Principal Rights',
    requirement: 'Right to Erasure (Right to be Forgotten)',
    governmentRef: 'DPDP Act 2023 - Section 12(2) | DPDP Rules 2025 - Rule 5',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 200 Cr for failing to erase data',
    actionIfNonCompliant: [
      'Build erasure request processing workflow',
      'Implement automated deletion across all systems and backups',
      'Document legitimate exceptions: legal compliance, ongoing disputes, tax records',
      'Provide erasure confirmation within 30 days',
      'Notify third parties to erase shared data',
    ],
    actionIfCompliant: 'Erasure process operational. Test deletion completeness quarterly.',
  },
  rights_4: {
    questionId: 'rights_4',
    category: 'Data Principal Rights',
    requirement: 'Grievance Redressal Mechanism',
    governmentRef: 'DPDP Act 2023 - Section 13 | DPDP Rules 2025 - Rule 6',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 200 Cr for inadequate grievance mechanism',
    actionIfNonCompliant: [
      'Appoint Grievance Officer with published contact details',
      'Create dedicated grievance channel (email, portal, toll-free number)',
      'Implement ticket tracking with 30-day response SLA',
      'Establish escalation path to senior management',
      'Publish grievance officer details on website and privacy notice',
    ],
    actionIfCompliant: 'Grievance mechanism operational. Monitor resolution times and satisfaction.',
  },

  // SECURITY SAFEGUARDS
  security_1: {
    questionId: 'security_1',
    category: 'Security Safeguards',
    requirement: 'Encryption at Rest',
    governmentRef: 'DPDP Act 2023 - Section 8(4) | DPDP Rules 2025 - Rule 6',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 250 Cr - HIGHEST PENALTY CATEGORY',
    actionIfNonCompliant: [
      'Implement AES-256 encryption for all databases containing personal data',
      'Enable Transparent Data Encryption (TDE) for SQL databases',
      'Encrypt file storage, backups, and archives',
      'Use hardware security modules (HSM) for key management',
      'Implement encryption for laptops and mobile devices with personal data',
    ],
    actionIfCompliant: 'Encryption at rest implemented. Conduct annual encryption audits.',
  },
  security_2: {
    questionId: 'security_2',
    category: 'Security Safeguards',
    requirement: 'Audit Logging and Retention',
    governmentRef: 'DPDP Rules 2025 - Rule 6(2) | Rule 12',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 250 Cr for inadequate security measures',
    actionIfNonCompliant: [
      'Log all access to personal data with: user ID, timestamp, action, record accessed',
      'Retain logs for minimum 1 year as per DPDP Rules',
      'Implement log integrity protection (write-once storage, digital signatures)',
      'Set up real-time alerting for suspicious access patterns',
      'Enable log export for regulatory requests',
    ],
    actionIfCompliant: 'Audit logging operational. Review logs monthly for anomalies.',
  },
  security_3: {
    questionId: 'security_3',
    category: 'Security Safeguards',
    requirement: 'Role-Based Access Controls',
    governmentRef: 'DPDP Act 2023 - Section 8(4) | DPDP Rules 2025 - Rule 6',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 250 Cr for inadequate access controls',
    actionIfNonCompliant: [
      'Implement RBAC with principle of least privilege',
      'Define roles with specific data access permissions',
      'Conduct quarterly access reviews and remove unnecessary access',
      'Implement privileged access management (PAM) for admin accounts',
      'Enable multi-factor authentication for all personal data access',
    ],
    actionIfCompliant: 'RBAC implemented. Conduct quarterly access certifications.',
  },
  security_4: {
    questionId: 'security_4',
    category: 'Security Safeguards',
    requirement: 'Tokenization and Data Masking',
    governmentRef: 'DPDP Act 2023 - Section 8(4) | DPDP Rules 2025 - Rule 6',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 250 Cr for exposing sensitive identifiers',
    actionIfNonCompliant: [
      'Implement tokenization for Aadhaar, PAN, and payment card data',
      'Mask sensitive data in non-production environments',
      'Use format-preserving encryption where tokenization not feasible',
      'Ensure display masking in UI (show only last 4 digits)',
      'Implement data masking for analytics and reporting',
    ],
    actionIfCompliant: 'Tokenization implemented. Review scope when adding new sensitive data types.',
  },

  // BREACH RESPONSE
  breach_1: {
    questionId: 'breach_1',
    category: 'Breach Response',
    requirement: 'Incident Response Plan',
    governmentRef: 'DPDP Act 2023 - Section 8(6) | DPDP Rules 2025 - Rule 7',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 200 Cr for breach notification failure',
    actionIfNonCompliant: [
      'Create documented incident response plan with roles and responsibilities',
      'Define breach detection and assessment procedures',
      'Establish communication templates for DPB and affected parties',
      'Conduct tabletop exercises quarterly',
      'Integrate with SOC/SIEM for automated breach detection',
    ],
    actionIfCompliant: 'IRP documented. Conduct annual plan review and tabletop exercises.',
  },
  breach_2: {
    questionId: 'breach_2',
    category: 'Breach Response',
    requirement: '72-Hour Breach Notification to DPB',
    governmentRef: 'DPDP Act 2023 - Section 8(6) | DPDP Rules 2025 - Rule 7',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 200 Cr for late or missed notification',
    actionIfNonCompliant: [
      '72-hour clock starts from DETECTION, not confirmation',
      'Pre-draft notification templates with placeholders',
      'Establish 24/7 escalation path to authorized reporters',
      'Create Data Protection Board contact database',
      'Implement breach severity classification matrix',
    ],
    actionIfCompliant: '72-hour capability established. Test notification process bi-annually.',
  },
  breach_3: {
    questionId: 'breach_3',
    category: 'Breach Response',
    requirement: 'Affected Party Notification',
    governmentRef: 'DPDP Act 2023 - Section 8(6) | DPDP Rules 2025 - Rule 7',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 200 Cr for failing to notify affected individuals',
    actionIfNonCompliant: [
      'Create notification templates covering: breach nature, data involved, consequences',
      'Include recommended protective actions for users',
      'Establish communication channels: email, SMS, in-app, public notice',
      'Provide helpline/FAQ for affected individuals',
      'Document notification evidence (delivery receipts)',
    ],
    actionIfCompliant: 'Affected party notification process documented. Test communication channels.',
  },

  // CHILDREN'S DATA
  children_1: {
    questionId: 'children_1',
    category: "Children's Data",
    requirement: 'Verifiable Parental Consent',
    governmentRef: 'DPDP Act 2023 - Section 9 | DPDP Rules 2025 - Rule 8',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 200 Cr for processing children data without parental consent',
    actionIfNonCompliant: [
      'Implement age-gate at registration asking date of birth',
      'For users under 18, trigger parental consent flow',
      'Verification methods: DigiLocker token, government ID upload, video verification',
      'Obtain consent from identified parent/guardian only',
      'Maintain consent records with verification evidence',
    ],
    actionIfCompliant: 'Parental consent mechanism operational. Audit consent quality quarterly.',
  },
  children_2: {
    questionId: 'children_2',
    category: "Children's Data",
    requirement: 'No Behavioral Tracking of Children',
    governmentRef: 'DPDP Act 2023 - Section 9(2) | DPDP Rules 2025 - Rule 8',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 200 Cr - ABSOLUTE PROHIBITION',
    actionIfNonCompliant: [
      'IMMEDIATELY disable all tracking for users flagged as under 18',
      'Remove children from advertising audiences and lookalike models',
      'Disable behavioral cookies and analytics for children sessions',
      'No profiling, recommendation engines based on children behavior',
      'Audit ad tech stack for any children data processing',
    ],
    actionIfCompliant: 'Children tracking disabled. Conduct quarterly audits for compliance.',
  },
  children_3: {
    questionId: 'children_3',
    category: "Children's Data",
    requirement: 'Age Verification Mechanisms',
    governmentRef: 'DPDP Act 2023 - Section 9 | DPDP Rules 2025 - Rule 8',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 200 Cr for inadequate age verification',
    actionIfNonCompliant: [
      'Self-declaration alone may be insufficient for high-risk services',
      'Implement ID verification for gaming, social media, dating apps',
      'Use age estimation technology as supplementary measure',
      'Design neutral age-gates (no incentive to lie about age)',
      'Maintain age verification audit trail',
    ],
    actionIfCompliant: 'Age verification implemented. Review effectiveness based on user demographics.',
  },

  // THIRD-PARTY & TRANSFERS
  thirdparty_1: {
    questionId: 'thirdparty_1',
    category: 'Third-Party & Transfers',
    requirement: 'Data Processing Agreements',
    governmentRef: 'DPDP Act 2023 - Section 8(2) | DPDP Rules 2025 - Rule 9',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 250 Cr for non-compliant third-party processing',
    actionIfNonCompliant: [
      'Inventory all third parties processing personal data on your behalf',
      'Execute DPDP-compliant DPAs covering: scope, security, breach notification',
      'Include audit rights and sub-processor approval requirements',
      'Require data deletion upon contract termination',
      'Mandate SOC 2 or ISO 27001 certification from processors',
    ],
    actionIfCompliant: 'DPAs in place. Conduct annual DPA reviews and renewals.',
  },
  thirdparty_2: {
    questionId: 'thirdparty_2',
    category: 'Third-Party & Transfers',
    requirement: 'Third-Party Security Due Diligence',
    governmentRef: 'DPDP Act 2023 - Section 8(4) | DPDP Rules 2025 - Rule 9',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Vicarious liability - Up to Rs. 250 Cr for processor failures',
    actionIfNonCompliant: [
      'Conduct security assessment before onboarding new vendors',
      'Require security questionnaires and penetration test reports',
      'Request SOC 2 Type II or ISO 27001 certifications',
      'Implement vendor risk scoring and tiered review frequency',
      'Include right to audit in all DPAs',
    ],
    actionIfCompliant: 'Vendor due diligence process established. Conduct annual re-assessments.',
  },
  thirdparty_3: {
    questionId: 'thirdparty_3',
    category: 'Third-Party & Transfers',
    requirement: 'Cross-Border Transfer Compliance',
    governmentRef: 'DPDP Act 2023 - Section 16 | DPDP Rules 2025 - Rule 10',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 250 Cr for unauthorized transfers',
    actionIfNonCompliant: [
      'Document all cross-border data flows with destination countries',
      'Check Central Government blacklist for prohibited destinations',
      'Implement data localization for sensitive categories if required',
      'Include cross-border transfer provisions in DPAs',
      'Consider local processing options to minimize transfers',
    ],
    actionIfCompliant: 'Cross-border compliance documented. Monitor government notifications for blacklist updates.',
  },
};

export const DPDP_CATEGORY_LABELS: Record<string, string> = {
  inventory: 'Data Inventory & Mapping',
  consent: 'Consent Management',
  notices: 'Privacy Notices',
  rights: 'Data Principal Rights',
  security: 'Security Safeguards',
  breach: 'Breach Response',
  children: "Children's Data",
  thirdparty: 'Third-Party & Transfers',
};
