/**
 * DPDP Compliance Rules for PDF Report Generation
 * Digital Personal Data Protection Act 2023 & DPDP Rules 2025
 */

import { ALL_DPDP_QUESTIONS } from '../assessments/dpdp-questions';

export interface DPDPComplianceRule {
  questionId: string;
  category: string;
  requirement: string;
  governmentRef: string;
  officialLink: string;
  deadline: string;
  penalty: string;
  actionIfNonCompliant: string[];
  actionIfCompliant: string;
}

export const DPDP_COMPLIANCE_RULES: Record<string, DPDPComplianceRule> = {
  // ============================================================================
  // CONSENT MANAGEMENT (consent_1 through consent_9)
  // ============================================================================
  consent_1: {
    questionId: 'consent_1',
    category: 'Consent Management',
    requirement: 'Granular and Purpose-Specific Consent',
    governmentRef: 'DPDP Act 2023 - Section 6(1), 6(3) | DPDP Rules 2025 - Rule 3(1)',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 50 Cr per violation',
    actionIfNonCompliant: [
      'Replace bundled consent checkboxes with separate consent for each purpose',
      'Pre-ticked boxes are INVALID - implement unchecked default states',
      'Separate consent required for: service delivery, marketing, analytics, profiling',
      'Implement consent versioning to track which version user agreed to',
      'Create consent preference centre allowing granular control',
    ],
    actionIfCompliant: 'Granular consent implemented. Conduct annual consent UX audit for dark patterns.',
  },
  consent_2: {
    questionId: 'consent_2',
    category: 'Consent Management',
    requirement: 'Easy Consent Withdrawal (Withdrawal Parity)',
    governmentRef: 'DPDP Act 2023 - Section 6(4) | DPDP Rules 2025 - Rule 3(3)',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 50 Cr for making withdrawal difficult',
    actionIfNonCompliant: [
      'Implement one-click consent withdrawal matching consent mechanism',
      'Create self-service consent management portal accessible from user account',
      'Do NOT require: login, multiple steps, email verification, or phone calls for withdrawal',
      'Process withdrawal within 24 hours and send confirmation',
      'Stop processing immediately upon withdrawal (except legal obligations)',
    ],
    actionIfCompliant: 'Withdrawal parity achieved. Monitor withdrawal completion times monthly.',
  },
  consent_3: {
    questionId: 'consent_3',
    category: 'Consent Management',
    requirement: 'Multilingual Privacy Notices',
    governmentRef: 'DPDP Act 2023 - Section 5(1) | DPDP Rules 2025 - Rule 3',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 50 Cr for non-compliant notices',
    actionIfNonCompliant: [
      'Provide notices in Hindi and English at minimum',
      'Add regional languages based on user demographics (22 scheduled languages)',
      'Implement language detection and automatic locale selection',
      'Ensure translations are legally accurate, not just machine-translated',
      'Test notices with native speakers for clarity',
    ],
    actionIfCompliant: 'Multilingual notices available. Review translations when notices change.',
  },
  consent_4: {
    questionId: 'consent_4',
    category: 'Consent Management',
    requirement: 'Purpose Limitation Compliance',
    governmentRef: 'DPDP Act 2023 - Section 6(1) | DPDP Rules 2025 - Rule 3',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 50 Cr for processing beyond consented purposes',
    actionIfNonCompliant: [
      'Document all data processing activities against their original consent purposes',
      'Implement technical controls preventing use beyond consented scope',
      'Create workflow requiring fresh consent for new processing purposes',
      'Audit data usage quarterly for purpose creep',
      'Train staff on purpose limitation requirements',
    ],
    actionIfCompliant: 'Purpose limitation controls operational. Conduct quarterly purpose audits.',
  },
  consent_5: {
    questionId: 'consent_5',
    category: 'Consent Management',
    requirement: 'Consent Record Keeping',
    governmentRef: 'DPDP Act 2023 - Section 6 | DPDP Rules 2025 - Rule 3',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Unable to demonstrate lawful processing - Up to Rs. 250 Cr',
    actionIfNonCompliant: [
      'Implement consent logging with: timestamp, IP address, user agent, consent version',
      'Store consent records for minimum 7 years (recommended)',
      'Enable audit trail retrieval by user ID or date range',
      'Include proof of what user was shown at time of consent',
      'Implement tamper-proof consent storage',
    ],
    actionIfCompliant: 'Consent logs maintained. Ensure log backup and disaster recovery.',
  },
  consent_6: {
    questionId: 'consent_6',
    category: 'Consent Management',
    requirement: 'Re-consent for Policy Changes',
    governmentRef: 'DPDP Act 2023 - Section 5, 6 | DPDP Rules 2025',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Processing without valid consent - Up to Rs. 50 Cr',
    actionIfNonCompliant: [
      'Implement notice version control with change tracking',
      'Notify users of material changes via email and in-app notification',
      'Re-obtain consent when adding new processing purposes',
      'Maintain archive of all previous notice versions with dates',
      'Give users 30-day notice period before changes take effect',
    ],
    actionIfCompliant: 'Re-consent process documented. Trigger re-notification when privacy practices change.',
  },
  consent_7: {
    questionId: 'consent_7',
    category: 'Consent Management',
    requirement: 'Cookie and Tracking Consent',
    governmentRef: 'DPDP Act 2023 - Section 6 | IT Rules 2011',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 50 Cr for non-consensual tracking',
    actionIfNonCompliant: [
      'Implement cookie consent banner with granular category options',
      'Allow users to opt-in/out of each cookie type separately',
      'Essential cookies only until consent is granted',
      'Store cookie consent preferences and honor them across sessions',
      'Provide easy access to change cookie preferences later',
    ],
    actionIfCompliant: 'Cookie consent mechanism operational. Audit cookie compliance quarterly.',
  },
  consent_8: {
    questionId: 'consent_8',
    category: 'Consent Management',
    requirement: 'Third-Party Data Sharing Consent',
    governmentRef: 'DPDP Act 2023 - Section 6(1), 8(2) | DPDP Rules 2025 - Rule 9',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 50 Cr for unauthorized third-party sharing',
    actionIfNonCompliant: [
      'Obtain separate, explicit consent before sharing data with any third party',
      'Clearly identify each third party and their purpose in consent flow',
      'Implement data processing agreements with all third parties',
      'Provide users visibility into which third parties have their data',
      'Enable users to revoke third-party sharing consent independently',
    ],
    actionIfCompliant: 'Third-party consent controls operational. Review vendor list quarterly.',
  },
  consent_9: {
    questionId: 'consent_9',
    category: 'Consent Management',
    requirement: 'Consent Version History Tracking',
    governmentRef: 'DPDP Act 2023 - Section 6 | Best Practice',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Inability to demonstrate compliance - Up to Rs. 50 Cr',
    actionIfNonCompliant: [
      'Implement version control for all consent forms and privacy notices',
      'Track which consent version each user agreed to',
      'Store historical versions with effective date ranges',
      'Enable retrieval of consent state at any point in time',
      'Create dashboard for consent version analytics',
    ],
    actionIfCompliant: 'Consent versioning implemented. Archive all versions indefinitely.',
  },

  // ============================================================================
  // SECURITY SAFEGUARDS (security_1 through security_9)
  // ============================================================================
  security_1: {
    questionId: 'security_1',
    category: 'Security Safeguards',
    requirement: 'Encryption at Rest',
    governmentRef: 'DPDP Act 2023 - Section 8(4) | DPDP Rules 2025 - Rule 6',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 250 Cr - HIGHEST PENALTY CATEGORY',
    actionIfNonCompliant: [
      'Implement AES-256 encryption for all databases containing personal data',
      'Enable Transparent Data Encryption (TDE) for SQL databases',
      'Encrypt file storage, backups, and archives',
      'Use hardware security modules (HSM) for key management',
      'Implement encryption for laptops and mobile devices with personal data',
    ],
    actionIfCompliant: 'Encryption at rest implemented. Conduct annual encryption audits.',
  },
  security_2: {
    questionId: 'security_2',
    category: 'Security Safeguards',
    requirement: 'Encryption in Transit',
    governmentRef: 'DPDP Act 2023 - Section 8(4) | DPDP Rules 2025 - Rule 6',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 250 Cr for inadequate transit security',
    actionIfNonCompliant: [
      'Implement TLS 1.3 for all external data transfers (minimum TLS 1.2)',
      'Enable HTTPS everywhere - no exceptions for any personal data',
      'Disable weak ciphers and SSL/early TLS versions',
      'Implement certificate pinning for mobile apps',
      'Use encrypted connections for internal services handling personal data',
    ],
    actionIfCompliant: 'Transit encryption operational. Monitor cipher suite strength quarterly.',
  },
  security_3: {
    questionId: 'security_3',
    category: 'Security Safeguards',
    requirement: 'Tokenization and Data Masking',
    governmentRef: 'DPDP Act 2023 - Section 8(4) | DPDP Rules 2025 - Rule 6',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 250 Cr for exposing sensitive identifiers',
    actionIfNonCompliant: [
      'Implement tokenization for Aadhaar, PAN, and payment card data',
      'Mask sensitive data in non-production environments',
      'Use format-preserving encryption where tokenization not feasible',
      'Ensure display masking in UI (show only last 4 digits)',
      'Implement data masking for analytics and reporting',
    ],
    actionIfCompliant: 'Tokenization implemented. Review scope when adding new sensitive data types.',
  },
  security_4: {
    questionId: 'security_4',
    category: 'Security Safeguards',
    requirement: 'Role-Based Access Controls',
    governmentRef: 'DPDP Act 2023 - Section 8(4) | DPDP Rules 2025 - Rule 6',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 250 Cr for inadequate access controls',
    actionIfNonCompliant: [
      'Implement RBAC with principle of least privilege',
      'Define roles with specific data access permissions',
      'Conduct quarterly access reviews and remove unnecessary access',
      'Implement privileged access management (PAM) for admin accounts',
      'Enable multi-factor authentication for all personal data access',
    ],
    actionIfCompliant: 'RBAC implemented. Conduct quarterly access certifications.',
  },
  security_5: {
    questionId: 'security_5',
    category: 'Security Safeguards',
    requirement: 'Audit Logging and Retention',
    governmentRef: 'DPDP Rules 2025 - Rule 6(2) | Rule 12',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 250 Cr for inadequate security measures',
    actionIfNonCompliant: [
      'Log all access to personal data with: user ID, timestamp, action, record accessed',
      'Retain logs for minimum 1 year as per DPDP Rules',
      'Implement log integrity protection (write-once storage, digital signatures)',
      'Set up real-time alerting for suspicious access patterns',
      'Enable log export for regulatory requests',
    ],
    actionIfCompliant: 'Audit logging operational. Review logs monthly for anomalies.',
  },
  security_6: {
    questionId: 'security_6',
    category: 'Security Safeguards',
    requirement: 'Intrusion Detection Systems',
    governmentRef: 'DPDP Act 2023 - Section 8(4) | IT Act 2000',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 250 Cr for security failures leading to breach',
    actionIfNonCompliant: [
      'Deploy network-based intrusion detection/prevention systems (IDS/IPS)',
      'Implement endpoint detection and response (EDR) on all systems',
      'Configure 24/7 monitoring with SOC capabilities',
      'Establish automated threat response playbooks',
      'Integrate threat intelligence feeds for proactive defense',
    ],
    actionIfCompliant: 'IDS/IPS operational. Review detection rules and tune alerts monthly.',
  },
  security_7: {
    questionId: 'security_7',
    category: 'Security Safeguards',
    requirement: 'Backup and Recovery Testing',
    governmentRef: 'DPDP Act 2023 - Section 8(4) | Best Practice',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 250 Cr for inability to recover from incidents',
    actionIfNonCompliant: [
      'Implement automated backup for all personal data repositories',
      'Store backups encrypted and in geographically separate location',
      'Test backup restoration quarterly with documented results',
      'Define and test RTO/RPO targets for critical systems',
      'Document disaster recovery procedures and train responsible staff',
    ],
    actionIfCompliant: 'Backup and recovery tested. Conduct quarterly restoration drills.',
  },
  security_8: {
    questionId: 'security_8',
    category: 'Security Safeguards',
    requirement: 'Vulnerability Assessment',
    governmentRef: 'DPDP Act 2023 - Section 8(4) | CERT-In Guidelines',
    officialLink: 'https://www.cert-in.org.in',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 250 Cr for security negligence',
    actionIfNonCompliant: [
      'Implement continuous vulnerability scanning for all public-facing assets',
      'Conduct quarterly penetration testing by certified third parties',
      'Establish vulnerability remediation SLAs (critical: 72hrs, high: 7 days)',
      'Subscribe to security advisories for all software components',
      'Document and track all vulnerabilities to closure',
    ],
    actionIfCompliant: 'Vulnerability management operational. Maintain <30 day remediation cycle.',
  },
  security_9: {
    questionId: 'security_9',
    category: 'Security Safeguards',
    requirement: 'Secure Software Development (SSDLC)',
    governmentRef: 'DPDP Act 2023 - Section 8(4) | OWASP Best Practice',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 250 Cr for security-by-design failures',
    actionIfNonCompliant: [
      'Implement security requirements in all development projects',
      'Conduct threat modeling during design phase',
      'Enable static code analysis (SAST) in CI/CD pipeline',
      'Perform security testing before production deployment',
      'Train developers on secure coding practices annually',
    ],
    actionIfCompliant: 'SSDLC embedded. Review security gates in SDLC annually.',
  },

  // ============================================================================
  // DATA PRINCIPAL RIGHTS (rights_1 through rights_6)
  // ============================================================================
  rights_1: {
    questionId: 'rights_1',
    category: 'Data Principal Rights',
    requirement: 'Right to Access (Data Subject Access Request)',
    governmentRef: 'DPDP Act 2023 - Section 11 | DPDP Rules 2025 - Rule 5',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 50 Cr for failing to respond to requests',
    actionIfNonCompliant: [
      'Build DSAR portal for users to submit access requests',
      'Implement identity verification for requesters',
      'Create 90-day SLA tracking with escalation procedures',
      'Provide: data summary, processing purposes, third-party disclosures',
      'Enable data export in machine-readable format (JSON, CSV)',
    ],
    actionIfCompliant: 'DSAR process operational. Monitor response times and completion rates.',
  },
  rights_2: {
    questionId: 'rights_2',
    category: 'Data Principal Rights',
    requirement: 'Right to Correction',
    governmentRef: 'DPDP Act 2023 - Section 12 | DPDP Rules 2025 - Rule 5',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 50 Cr for failing to correct inaccurate data',
    actionIfNonCompliant: [
      'Provide self-service profile editing for basic fields',
      'Create correction request workflow for restricted fields',
      'Maintain audit trail of all corrections with timestamps',
      'Propagate corrections to all systems including backups',
      'Notify third parties who received incorrect data',
    ],
    actionIfCompliant: 'Correction process available. Ensure correction propagation to downstream systems.',
  },
  rights_3: {
    questionId: 'rights_3',
    category: 'Data Principal Rights',
    requirement: 'Right to Erasure (Right to be Forgotten)',
    governmentRef: 'DPDP Act 2023 - Section 12(2) | DPDP Rules 2025 - Rule 5',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 50 Cr for failing to erase data',
    actionIfNonCompliant: [
      'Build erasure request processing workflow',
      'Implement automated deletion across all systems and backups',
      'Document legitimate exceptions: legal compliance, ongoing disputes, tax records',
      'Provide erasure confirmation within 30 days',
      'Notify third parties to erase shared data',
    ],
    actionIfCompliant: 'Erasure process operational. Test deletion completeness quarterly.',
  },
  rights_4: {
    questionId: 'rights_4',
    category: 'Data Principal Rights',
    requirement: 'Grievance Redressal Mechanism',
    governmentRef: 'DPDP Act 2023 - Section 13 | DPDP Rules 2025 - Rule 6',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 50 Cr for inadequate grievance mechanism',
    actionIfNonCompliant: [
      'Appoint Grievance Officer with published contact details',
      'Create dedicated grievance channel (email, portal, toll-free number)',
      'Implement ticket tracking with 30-day response SLA',
      'Establish escalation path to senior management',
      'Publish grievance officer details on website and privacy notice',
    ],
    actionIfCompliant: 'Grievance mechanism operational. Monitor resolution times and satisfaction.',
  },
  rights_5: {
    questionId: 'rights_5',
    category: 'Data Principal Rights',
    requirement: 'Timely Response to Rights Requests',
    governmentRef: 'DPDP Act 2023 - Section 11, 12 | DPDP Rules 2025 - Rule 5',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 50 Cr for unreasonable delays',
    actionIfNonCompliant: [
      'Define and publish response timelines for each request type',
      'Implement request tracking with automated reminders',
      'Create escalation process for requests approaching deadline',
      'Acknowledge receipt of all requests within 48 hours',
      'Provide regular status updates for complex requests',
    ],
    actionIfCompliant: 'Response timelines met. Track and report SLA metrics monthly.',
  },
  rights_6: {
    questionId: 'rights_6',
    category: 'Data Principal Rights',
    requirement: 'Nomination of Representative',
    governmentRef: 'DPDP Act 2023 - Section 14 | DPDP Rules 2025 - Rule 5',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 50 Cr for not honoring nomination rights',
    actionIfNonCompliant: [
      'Create mechanism for users to nominate representative for rights exercise',
      'Verify nominee identity before processing requests',
      'Enable users to update or revoke nominations easily',
      'Process requests from nominated representatives with same priority',
      'Document nomination records with audit trail',
    ],
    actionIfCompliant: 'Nomination mechanism available. Review nomination policies annually.',
  },

  // ============================================================================
  // BREACH RESPONSE (breach_1 through breach_5)
  // ============================================================================
  breach_1: {
    questionId: 'breach_1',
    category: 'Breach Response',
    requirement: 'Incident Response Plan',
    governmentRef: 'DPDP Act 2023 - Section 8(6) | DPDP Rules 2025 - Rule 7',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 200 Cr for breach notification failure',
    actionIfNonCompliant: [
      'Create documented incident response plan with roles and responsibilities',
      'Define breach detection and assessment procedures',
      'Establish communication templates for DPB and affected parties',
      'Conduct tabletop exercises quarterly',
      'Integrate with SOC/SIEM for automated breach detection',
    ],
    actionIfCompliant: 'IRP documented. Conduct annual plan review and tabletop exercises.',
  },
  breach_2: {
    questionId: 'breach_2',
    category: 'Breach Response',
    requirement: '72-Hour Breach Notification to DPB',
    governmentRef: 'DPDP Act 2023 - Section 8(6) | DPDP Rules 2025 - Rule 7',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 200 Cr for late or missed notification',
    actionIfNonCompliant: [
      '72-hour clock starts from DETECTION, not confirmation',
      'Pre-draft notification templates with placeholders',
      'Establish 24/7 escalation path to authorized reporters',
      'Create Data Protection Board contact database',
      'Implement breach severity classification matrix',
    ],
    actionIfCompliant: '72-hour capability established. Test notification process bi-annually.',
  },
  breach_3: {
    questionId: 'breach_3',
    category: 'Breach Response',
    requirement: 'Affected Party Notification',
    governmentRef: 'DPDP Act 2023 - Section 8(6) | DPDP Rules 2025 - Rule 7',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 200 Cr for failing to notify affected individuals',
    actionIfNonCompliant: [
      'Create notification templates covering: breach nature, data involved, consequences',
      'Include recommended protective actions for users',
      'Establish communication channels: email, SMS, in-app, public notice',
      'Provide helpline/FAQ for affected individuals',
      'Document notification evidence (delivery receipts)',
    ],
    actionIfCompliant: 'Affected party notification process documented. Test communication channels.',
  },
  breach_4: {
    questionId: 'breach_4',
    category: 'Breach Response',
    requirement: 'Security Incident Documentation',
    governmentRef: 'DPDP Act 2023 - Section 8 | CERT-In Guidelines',
    officialLink: 'https://www.cert-in.org.in',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 200 Cr for inadequate incident management',
    actionIfNonCompliant: [
      'Maintain comprehensive incident register with all security events',
      'Document: incident timeline, impact assessment, containment actions',
      'Record root cause analysis findings for each incident',
      'Track remediation actions to completion',
      'Generate incident reports for management and regulators',
    ],
    actionIfCompliant: 'Incident documentation maintained. Archive records for 7 years.',
  },
  breach_5: {
    questionId: 'breach_5',
    category: 'Breach Response',
    requirement: 'Post-Incident Review and Remediation',
    governmentRef: 'DPDP Act 2023 - Section 8(4) | Best Practice',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 200 Cr for repeat incidents from same cause',
    actionIfNonCompliant: [
      'Conduct post-incident review within 2 weeks of incident closure',
      'Document lessons learned and improvement recommendations',
      'Track remediation actions with assigned owners and deadlines',
      'Update security controls and procedures based on findings',
      'Report incident patterns to senior management quarterly',
    ],
    actionIfCompliant: 'Post-incident reviews conducted. Verify remediation effectiveness.',
  },

  // ============================================================================
  // CHILDREN'S DATA PROTECTION (children_1 through children_5)
  // ============================================================================
  children_1: {
    questionId: 'children_1',
    category: "Children's Data Protection",
    requirement: 'Verifiable Parental Consent',
    governmentRef: 'DPDP Act 2023 - Section 9 | DPDP Rules 2025 - Rule 8',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 200 Cr for processing children data without parental consent',
    actionIfNonCompliant: [
      'Implement age-gate at registration asking date of birth',
      'For users under 18, trigger parental consent flow',
      'Verification methods: DigiLocker token, government ID upload, video verification',
      'Obtain consent from identified parent/guardian only',
      'Maintain consent records with verification evidence',
    ],
    actionIfCompliant: 'Parental consent mechanism operational. Audit consent quality quarterly.',
  },
  children_2: {
    questionId: 'children_2',
    category: "Children's Data Protection",
    requirement: 'Age Verification Mechanisms',
    governmentRef: 'DPDP Act 2023 - Section 9 | DPDP Rules 2025 - Rule 8',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 200 Cr for inadequate age verification',
    actionIfNonCompliant: [
      'Self-declaration alone may be insufficient for high-risk services',
      'Implement ID verification for gaming, social media, dating apps',
      'Use age estimation technology as supplementary measure',
      'Design neutral age-gates (no incentive to lie about age)',
      'Maintain age verification audit trail',
    ],
    actionIfCompliant: 'Age verification implemented. Review effectiveness based on user demographics.',
  },
  children_3: {
    questionId: 'children_3',
    category: "Children's Data Protection",
    requirement: 'No Behavioral Tracking of Children',
    governmentRef: 'DPDP Act 2023 - Section 9(2) | DPDP Rules 2025 - Rule 8',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 200 Cr - ABSOLUTE PROHIBITION',
    actionIfNonCompliant: [
      'IMMEDIATELY disable all tracking for users flagged as under 18',
      'Remove children from advertising audiences and lookalike models',
      'Disable behavioral cookies and analytics for children sessions',
      'No profiling, recommendation engines based on children behavior',
      'Audit ad tech stack for any children data processing',
    ],
    actionIfCompliant: 'Children tracking disabled. Conduct quarterly audits for compliance.',
  },
  children_4: {
    questionId: 'children_4',
    category: "Children's Data Protection",
    requirement: "Deletion of Children's Data",
    governmentRef: 'DPDP Act 2023 - Section 9 | DPDP Rules 2025 - Rule 8',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 200 Cr for retaining children data improperly',
    actionIfNonCompliant: [
      'Implement mechanism for parents to request deletion of child data',
      'Automatically flag children accounts for data minimization',
      'Delete children data when consent is withdrawn or child ages out',
      'Propagate deletion to all systems including backups',
      'Confirm deletion to parent/guardian within 30 days',
    ],
    actionIfCompliant: 'Children data deletion process operational. Test quarterly.',
  },
  children_5: {
    questionId: 'children_5',
    category: "Children's Data Protection",
    requirement: 'Transparent Communication with Parents',
    governmentRef: 'DPDP Act 2023 - Section 9 | DPDP Rules 2025 - Rule 8',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 200 Cr for inadequate parental transparency',
    actionIfNonCompliant: [
      'Provide clear, child-appropriate privacy notice for young users',
      'Separately explain to parents what data is collected and why',
      'Notify parents of any changes to children data processing',
      'Provide parents dashboard to view and manage child account',
      'Use plain language avoiding legal jargon in all communications',
    ],
    actionIfCompliant: 'Parent communication implemented. Review notices annually for clarity.',
  },

  // ============================================================================
  // GOVERNANCE & RETENTION (gov_1 through gov_4)
  // ============================================================================
  gov_1: {
    questionId: 'gov_1',
    category: 'Governance & Retention',
    requirement: 'Data Protection Officer (DPO) Designation',
    governmentRef: 'DPDP Act 2023 - Section 10 | DPDP Rules 2025 - Rule 11',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 150 Cr for inadequate governance',
    actionIfNonCompliant: [
      'Appoint India-based Data Protection Officer (mandatory for SDFs)',
      'Ensure DPO has adequate authority and resources',
      'Publish DPO contact details in privacy notice and on website',
      'DPO must report to highest management level',
      'Provide DPO with independence to perform duties without interference',
    ],
    actionIfCompliant: 'DPO appointed and published. Review DPO effectiveness annually.',
  },
  gov_2: {
    questionId: 'gov_2',
    category: 'Governance & Retention',
    requirement: 'Data Retention Policy',
    governmentRef: 'DPDP Act 2023 - Section 8(5) | DPDP Rules 2025 - Rule 4',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 50 Cr for retaining data beyond necessary period',
    actionIfNonCompliant: [
      'Define retention periods for each data category aligned with legal requirements',
      'Consider: consent validity, contract duration, statutory obligations (7 years for financial)',
      'Implement automated deletion triggers when retention period expires',
      'Create exception process for legal holds and dispute resolution',
      'Document retention justification for each category',
    ],
    actionIfCompliant: 'Retention schedules defined. Implement automated purging and periodic compliance audits.',
  },
  gov_3: {
    questionId: 'gov_3',
    category: 'Governance & Retention',
    requirement: 'Records of Processing Activities (ROPA)',
    governmentRef: 'DPDP Act 2023 - Section 8(7) | DPDP Rules 2025 - Rule 3',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 50 Cr for inadequate documentation',
    actionIfNonCompliant: [
      'Create ROPA template with mandatory fields: processing purpose, data categories, retention periods',
      'Document legal basis for each processing activity (consent, contract, legal obligation)',
      'Record all third parties receiving personal data with their purposes',
      'Include security measures applied to each data category',
      'Designate ROPA owner and establish quarterly review process',
    ],
    actionIfCompliant: 'ROPA maintained. Ensure annual review and update upon any new processing activity.',
  },
  gov_4: {
    questionId: 'gov_4',
    category: 'Governance & Retention',
    requirement: 'Employee Data Protection Training',
    governmentRef: 'DPDP Act 2023 - Section 8 | Best Practice',
    officialLink: 'https://www.meity.gov.in/data-protection-framework',
    deadline: '13 May 2027',
    penalty: 'Up to Rs. 150 Cr for employee-caused violations',
    actionIfNonCompliant: [
      'Implement mandatory annual data protection training for all employees',
      'Specialized training for employees handling personal data',
      'Include DPDP Act requirements, breach response, data principal rights',
      'Track training completion and maintain attendance records',
      'Update training content when regulations change',
    ],
    actionIfCompliant: 'Training program operational. Review content annually and after regulatory changes.',
  },
};

// Category labels for display
export const DPDP_CATEGORY_LABELS: Record<string, string> = {
  consent: 'Consent Management',
  security: 'Security Safeguards',
  rights: 'Data Principal Rights',
  breach: 'Breach Response',
  children: "Children's Data Protection",
  governance: 'Governance & Retention',
};

// Penalty amounts by category for summary display
export const DPDP_CATEGORY_PENALTIES: Record<string, string> = {
  consent: 'Rs.50 Cr',
  security: 'Rs.250 Cr',
  rights: 'Rs.50 Cr',
  breach: 'Rs.200 Cr',
  children: 'Rs.200 Cr',
  governance: 'Rs.150 Cr',
};


// Derived from the single source of truth in dpdp-questions.ts
// so the two files can never diverge.
export const DPDP_COMPLIANCE_ANSWERS: Record<string, string> = Object.fromEntries(
  ALL_DPDP_QUESTIONS
    .filter(q => q.complianceAnswer != null)
    .map(q => [q.id, q.complianceAnswer as string])
);
