// ============================================================================
// Phase 1 — Applicability Questions (25 questions)
// Source: Research §3 (all 25 numbered questions)
// These are ALWAYS shown; answers build the ApplicabilityProfile.
// appliesWhen: always true for Phase-1 questions.
// ============================================================================

import type { AutoDealerQuestion, ApplicabilityProfile } from '@/types/auto-dealer'

const always = (_p: ApplicabilityProfile): boolean => true

export const APPLICABILITY_QUESTIONS: AutoDealerQuestion[] = [
  // --------------------------------------------------------------------------
  // Entity / Scale
  // --------------------------------------------------------------------------
  {
    id: 'AD_APP_001',
    phase: 1,
    text: 'What is the legal form of your dealership business?',
    helpText: 'This determines which filings apply (Companies Act, LLPIN, partnership deed) and your GST/income-tax filing category.',
    type: 'single_choice',
    options: [
      { value: 'proprietorship', label: 'Sole Proprietorship' },
      { value: 'partnership', label: 'Partnership Firm' },
      { value: 'llp', label: 'LLP (Limited Liability Partnership)' },
      { value: 'pvt_ltd', label: 'Private Limited Company' },
      { value: 'public_ltd', label: 'Public Limited Company' },
      { value: 'opc', label: 'One Person Company (OPC)' },
    ],
    weight: 5,
    complianceArea: 'companies_act',
    source: 'Research §3, PRD §5.2',
    gapTemplate: {
      finding: 'Legal form not provided — unable to determine Companies Act and tax-filing obligations.',
      recommendation: 'Confirm legal form; ensure CIN/LLPIN/PAN is correctly registered with MCA/tax authorities.',
      timeline: '30_days',
      penaltyExposure: 'N/A — informational',
    },
    compliantAnswers: ['proprietorship', 'partnership', 'llp', 'pvt_ltd', 'public_ltd', 'opc'],
    appliesWhen: always,
  },
  {
    id: 'AD_APP_002',
    phase: 1,
    text: 'Does your dealership hold a valid PAN, GSTIN in every state of operation, and CIN/LLPIN (if applicable)?',
    helpText: 'PAN is mandatory for all businesses. GSTIN is required in each state where you supply goods/services. CIN/LLPIN is required only for companies/LLPs.',
    type: 'single_choice',
    options: [
      { value: 'all_yes', label: 'Yes — all applicable registrations are live' },
      { value: 'partial', label: 'Partially — some registrations are pending or missing' },
      { value: 'no', label: 'No — none of the above' },
    ],
    weight: 8,
    complianceArea: 'gst',
    source: 'Research §3, Income Tax Act §139A, CGST Act §22',
    gapTemplate: {
      finding: 'One or more mandatory registrations (PAN / GSTIN / CIN) may be missing.',
      recommendation: 'Obtain PAN immediately via Income Tax portal. Register for GST in every state of supply. File INC-22 / LLP Form 5 if address change pending.',
      timeline: '30_days',
      penaltyExposure: 'GST: Rs.10,000 per supply or 10% of tax, whichever higher. PAN: Rs.10,000 u/s 272B IT Act.',
    },
    compliantAnswers: ['all_yes'],
    partiallyCompliantAnswers: ['partial'],
    appliesWhen: always,
  },
  {
    id: 'AD_APP_003',
    phase: 1,
    text: 'How many total workers does your dealership employ (on-rolls + contract + apprentices, across all outlets)?',
    helpText: 'Include all showroom staff, technicians, washers, security, F&B/canteen workers, and apprentices. This drives EPF, ESI, POSH, Bonus, Factories Act, and Contract Labour thresholds.',
    type: 'single_choice',
    options: [
      { value: 'lt_10',    label: 'Fewer than 10' },
      { value: '10_19',    label: '10 to 19' },
      { value: '20_49',    label: '20 to 49' },
      { value: '50_99',    label: '50 to 99' },
      { value: '100_299',  label: '100 to 299' },
      { value: '300_499',  label: '300 to 499' },
      { value: 'gte_500',  label: '500 or more' },
    ],
    weight: 10,
    complianceArea: 'wages',
    source: 'Research §3, PRD §5.2',
    gapTemplate: {
      finding: 'Employee count not confirmed — threshold-driven compliances cannot be assessed.',
      recommendation: 'Maintain an accurate headcount register (on-rolls + contract + apprentices) as required by Code on Wages.',
      timeline: '30_days',
      penaltyExposure: 'N/A — informational',
    },
    compliantAnswers: ['lt_10', '10_19', '20_49', '50_99', '100_299', '300_499', 'gte_500'],
    appliesWhen: always,
  },
  {
    id: 'AD_APP_004',
    phase: 1,
    text: 'How many of your employees are women?',
    helpText: 'Women employee count drives creche obligations (>=30 women under Factories Act / >=50 under Maternity Benefit), women-specific S&E provisions, and POSH IC composition requirements.',
    type: 'single_choice',
    options: [
      { value: 'lt_10',   label: 'Fewer than 10' },
      { value: '10_29',   label: '10 to 29' },
      { value: '30_49',   label: '30 to 49' },
      { value: 'gte_50',  label: '50 or more' },
    ],
    weight: 4,
    complianceArea: 'posh',
    source: 'Research §3, Factories Act §48, Maternity Benefit Act §11A',
    gapTemplate: {
      finding: 'Women employee count not confirmed — creche and maternity thresholds cannot be verified.',
      recommendation: 'Maintain gender-disaggregated headcount; review creche and maternity obligations.',
      timeline: '30_days',
      penaltyExposure: 'N/A — informational',
    },
    compliantAnswers: ['lt_10', '10_29', '30_49', 'gte_50'],
    appliesWhen: always,
  },
  {
    id: 'AD_APP_005',
    phase: 1,
    text: 'What is your dealership\'s approximate annual turnover (across all outlets)?',
    helpText: 'Turnover determines: e-invoicing (>Rs.5 cr), tax audit u/s 44AB (>Rs.1 cr), GSTR-9C reconciliation, TCS thresholds, and CSR applicability.',
    type: 'single_choice',
    options: [
      { value: 'lt_1cr',     label: 'Less than Rs.1 crore' },
      { value: '1cr_5cr',    label: 'Rs.1 crore to Rs.5 crore' },
      { value: '5cr_10cr',   label: 'Rs.5 crore to Rs.10 crore' },
      { value: '10cr_40cr',  label: 'Rs.10 crore to Rs.40 crore' },
      { value: '40cr_100cr', label: 'Rs.40 crore to Rs.100 crore' },
      { value: 'gt_100cr',   label: 'More than Rs.100 crore' },
    ],
    weight: 7,
    complianceArea: 'gst',
    source: 'Research §3, CGST Act §31A, IT Act §44AB',
    gapTemplate: {
      finding: 'Turnover bracket not confirmed — e-invoicing and tax audit obligations unverified.',
      recommendation: 'Confirm AATO with CA/finance team; set up e-invoicing if AATO >Rs.5 cr.',
      timeline: '30_days',
      penaltyExposure: 'N/A — informational',
    },
    compliantAnswers: ['lt_1cr', '1cr_5cr', '5cr_10cr', '10cr_40cr', '40cr_100cr', 'gt_100cr'],
    appliesWhen: always,
  },
  {
    id: 'AD_APP_006',
    phase: 1,
    text: 'In which state(s) / UTs does your dealership operate outlets?',
    helpText: 'List all states where you have showrooms or workshops. This determines which state-specific laws apply: Professional Tax, S&E rules, SPCB category, minimum wages schedules.',
    type: 'single_choice',
    options: [
      { value: 'MH', label: 'Maharashtra' },
      { value: 'KA', label: 'Karnataka' },
      { value: 'DL', label: 'Delhi NCT' },
      { value: 'TN', label: 'Tamil Nadu' },
      { value: 'TS', label: 'Telangana' },
      { value: 'AP', label: 'Andhra Pradesh' },
      { value: 'GJ', label: 'Gujarat' },
      { value: 'HR', label: 'Haryana' },
      { value: 'RJ', label: 'Rajasthan' },
      { value: 'UP', label: 'Uttar Pradesh' },
      { value: 'WB', label: 'West Bengal' },
      { value: 'MP', label: 'Madhya Pradesh' },
      { value: 'PB', label: 'Punjab' },
      { value: 'OD', label: 'Odisha' },
      { value: 'AS', label: 'Assam' },
      { value: 'other', label: 'Other / Multiple states' },
    ],
    weight: 6,
    complianceArea: 'professional_tax',
    source: 'Research §3, PRD §5.5',
    gapTemplate: {
      finding: 'State of operation not confirmed — state-specific obligations (PT, S&E, min wages) unverified.',
      recommendation: 'Ensure S&E registration and PT registration in every state of operation.',
      timeline: '30_days',
      penaltyExposure: 'N/A — informational',
    },
    compliantAnswers: ['MH','KA','DL','TN','TS','AP','GJ','HR','RJ','UP','WB','MP','PB','OD','AS','other'],
    appliesWhen: always,
  },
  {
    id: 'AD_APP_007',
    phase: 1,
    text: 'How many physical outlets (showrooms / workshops / spares stores) does your dealership operate?',
    helpText: 'Each outlet may need its own S&E registration, Trade Certificate, GSTIN (if in different state), and display obligations.',
    type: 'single_choice',
    options: [
      { value: '1',    label: '1 outlet' },
      { value: '2_3',  label: '2 to 3 outlets' },
      { value: '4_10', label: '4 to 10 outlets' },
      { value: 'gt10', label: 'More than 10 outlets' },
    ],
    weight: 5,
    complianceArea: 's_and_e',
    source: 'Research §3',
    gapTemplate: {
      finding: 'Outlet count not confirmed — multi-location compliance obligations unverified.',
      recommendation: 'Ensure each outlet has its own S&E registration, Trade Certificate, and applicable state registrations.',
      timeline: '30_days',
      penaltyExposure: 'N/A — informational',
    },
    compliantAnswers: ['1', '2_3', '4_10', 'gt10'],
    appliesWhen: always,
  },

  // --------------------------------------------------------------------------
  // Vehicle Type & Business Mix
  // --------------------------------------------------------------------------
  {
    id: 'AD_APP_008',
    phase: 1,
    text: 'Which categories of vehicles does your dealership sell or service?',
    helpText: 'This drives Trade Certificate class, HSRP obligations, GST rate verification, BIS helmet/tyre requirements, and ELV registration.',
    type: 'single_choice',
    options: [
      { value: '2w_only',       label: '2-Wheeler only (bikes, scooters, mopeds)' },
      { value: '4w_only',       label: '4-Wheeler only (cars, SUVs, MPVs)' },
      { value: 'both_2w_4w',    label: 'Both 2-Wheeler and 4-Wheeler' },
      { value: 'commercial',    label: 'Commercial vehicles (trucks, buses, 3-wheelers)' },
      { value: 'ev_only',       label: 'Electric Vehicles only' },
      { value: 'mixed',         label: 'Mixed (multiple of the above)' },
    ],
    weight: 8,
    complianceArea: 'trade_certificate',
    source: 'Research §3, CMVR Rule 33',
    gapTemplate: {
      finding: 'Vehicle category not confirmed — Trade Certificate class and HSRP obligations unverified.',
      recommendation: 'Verify Form 17 covers all vehicle classes being sold; update VAHAN if adding new class.',
      timeline: '30_days',
      penaltyExposure: 'N/A — informational',
    },
    compliantAnswers: ['2w_only', '4w_only', 'both_2w_4w', 'commercial', 'ev_only', 'mixed'],
    appliesWhen: always,
  },
  {
    id: 'AD_APP_009',
    phase: 1,
    text: 'Which OEM(s) do you represent as an authorised dealer?',
    helpText: 'OEM relationship drives Form 16A authorisation display, OEM trademark use, and recall obligations.',
    type: 'single_choice',
    options: [
      { value: 'maruti',   label: 'Maruti Suzuki' },
      { value: 'hyundai',  label: 'Hyundai / Kia' },
      { value: 'tata',     label: 'Tata Motors' },
      { value: 'mahindra', label: 'Mahindra' },
      { value: 'honda_4w', label: 'Honda Cars' },
      { value: 'toyota',   label: 'Toyota' },
      { value: 'honda_2w', label: 'Honda Motorcycles' },
      { value: 'hero',     label: 'Hero MotoCorp' },
      { value: 'bajaj',    label: 'Bajaj Auto' },
      { value: 'tvs',      label: 'TVS Motor' },
      { value: 'multiple', label: 'Multiple OEMs' },
      { value: 'other',    label: 'Other' },
    ],
    weight: 4,
    complianceArea: 'trade_certificate',
    source: 'Research §3',
    gapTemplate: {
      finding: 'OEM information not provided.',
      recommendation: 'Confirm Form 16A authorisation letter from OEM is current and displayed.',
      timeline: '30_days',
      penaltyExposure: 'N/A — informational',
    },
    compliantAnswers: ['maruti','hyundai','tata','mahindra','honda_4w','toyota','honda_2w','hero','bajaj','tvs','multiple','other'],
    appliesWhen: always,
  },
  {
    id: 'AD_APP_010',
    phase: 1,
    text: 'Do you conduct test rides / test drives on public roads?',
    helpText: 'Test drives on public roads require a valid Trade Plate (trade registration mark on Form 17), a licensed driver, and appropriate third-party insurance. CMVR Rule 42 strictly prohibits use of trade plates by third parties.',
    type: 'yes_no',
    weight: 7,
    complianceArea: 'trade_certificate',
    source: 'Research §3, CMVR Rule 42',
    gapTemplate: {
      finding: 'Test drives conducted on public roads without confirmed Trade Certificate compliance.',
      recommendation: 'Ensure every test drive uses a trade-registered plate, is driven by a licensed employee, and vehicle has valid insurance on trade plate.',
      timeline: '30_days',
      penaltyExposure: 'Rs.1,000 to Rs.5,000 + seizure under MV Act s.177 for unregistered vehicle on road',
    },
    compliantAnswers: ['yes', 'no'],
    appliesWhen: always,
  },
  {
    id: 'AD_APP_011',
    phase: 1,
    text: 'Do you operate a workshop or service centre on your premises (even minor servicing)?',
    helpText: 'A workshop — even minor oil-change or tyre-fitting — may constitute a "factory" or trigger SPCB CTO requirements depending on worker count and power load. This is the key branch point for Phase 3 questions.',
    type: 'yes_no',
    weight: 9,
    complianceArea: 'factories_osh',
    source: 'Research §3, Factories Act §2(m)',
    gapTemplate: {
      finding: 'Workshop operations exist but Factories Act / OSH Code applicability not assessed.',
      recommendation: 'Determine if workshop crosses Factories Act threshold (10+ workers with power, or 20+ without). Obtain Factory Licence Form 4 if applicable.',
      timeline: '90_days',
      penaltyExposure: 'Up to Rs.5 lakh; 2 yr imprisonment for hazardous-process breach (Factories Act §92)',
    },
    compliantAnswers: ['yes', 'no'],
    appliesWhen: always,
  },
  {
    id: 'AD_APP_012',
    phase: 1,
    text: 'Which workshop services do you provide? (Select all that apply)',
    helpText: 'Body-shop / paint booth triggers SPCB Air Consent, HW sludge authorisation, and PESO paint-storage rules. EV repair triggers battery-waste and electrical safety obligations.',
    type: 'multi_choice',
    options: [
      { value: 'general_service',   label: 'General service / periodic maintenance' },
      { value: 'body_shop_paint',   label: 'Body-shop and spray-painting / paint booth' },
      { value: 'engine_overhaul',   label: 'Engine overhaul / transmission' },
      { value: 'ev_repair',         label: 'EV battery servicing / repair' },
      { value: 'tyres',             label: 'Tyre fitting and wheel balancing' },
      { value: 'glass',             label: 'Glass repair / windshield replacement' },
      { value: 'electricals',       label: 'Auto-electrical / ECU diagnostics' },
      { value: 'none',              label: 'No workshop — showroom / spares only' },
    ],
    weight: 7,
    complianceArea: 'factories_osh',
    source: 'Research §3, HOWM Rules 2016',
    gapTemplate: {
      finding: 'Workshop services not confirmed — SPCB, HW, and PESO obligations cannot be assessed.',
      recommendation: 'List all workshop services to identify environmental and safety compliance requirements.',
      timeline: '30_days',
      penaltyExposure: 'N/A — informational',
    },
    compliantAnswers: ['general_service','body_shop_paint','engine_overhaul','ev_repair','tyres','glass','electricals','none'],
    appliesWhen: always,
  },
  {
    id: 'AD_APP_013',
    phase: 1,
    text: 'Do you operate a Pollution Under Control (PUC) checking centre on your premises?',
    helpText: 'PUC centres require authorisation from the RTO and display of valid certificate. Failure to maintain calibration logs can attract suspension.',
    type: 'yes_no',
    weight: 4,
    complianceArea: 'trade_certificate',
    source: 'Research §3, CMVR Rule 116',
    gapTemplate: {
      finding: 'PUC centre operated without confirming RTO authorisation status.',
      recommendation: 'Verify PUC centre authorisation is valid; maintain calibration records.',
      timeline: '30_days',
      penaltyExposure: 'Suspension of PUC centre authorisation; Rs.10,000 fine',
    },
    compliantAnswers: ['yes', 'no'],
    appliesWhen: always,
  },
  {
    id: 'AD_APP_014',
    phase: 1,
    text: 'Do you sell extended warranty, accessories, fuel additives, or other add-on products?',
    helpText: 'Accessories must display MRP per Legal Metrology Act. Extended warranty sold on behalf of OEM may need separate IRDAI scrutiny. This also affects Consumer Protection obligations.',
    type: 'yes_no',
    weight: 4,
    complianceArea: 'consumer_protection',
    source: 'Research §3, Consumer Protection Act 2019',
    gapTemplate: {
      finding: 'Accessories / add-on sales confirmed but MRP display and Consumer Protection compliance unverified.',
      recommendation: 'Ensure all accessories display MRP; do not charge above MRP; maintain price list for Right to Repair.',
      timeline: '30_days',
      penaltyExposure: 'Up to Rs.1 lakh per violation under Legal Metrology Act; CCPA can levy Rs.10 lakh (first) to Rs.50 lakh (repeat) for unfair trade practice',
    },
    compliantAnswers: ['yes', 'no'],
    appliesWhen: always,
  },
  {
    id: 'AD_APP_015',
    phase: 1,
    text: 'Do you operate or own a Registered Vehicle Scrapping Facility (RVSF) or collection centre for end-of-life vehicles?',
    helpText: 'RVSF operations require separate registration under ELV Rules 2025 and CPCB environmental clearance. Even a "collection centre" role triggers ELV producer/dismantler obligations.',
    type: 'yes_no',
    weight: 6,
    complianceArea: 'elv',
    source: 'Research §3, ELV Rules 2025 S.O. 98(E)',
    gapTemplate: {
      finding: 'RVSF / collection centre operated — ELV Rules 2025 registration status unverified.',
      recommendation: 'Register RVSF with SPCB; obtain CPCB certificate. Route all dealer demo/test fleet ELVs to registered RVSFs only.',
      timeline: '90_days',
      penaltyExposure: 'Rs.10 lakh to Rs.15 lakh per contravention + Rs.10 lakh continuing; up to 3 yr imprisonment',
    },
    compliantAnswers: ['yes', 'no'],
    appliesWhen: always,
  },

  // --------------------------------------------------------------------------
  // Premises
  // --------------------------------------------------------------------------
  {
    id: 'AD_APP_016',
    phase: 1,
    text: 'What is the approximate built-up area of your showroom and workshop?',
    helpText: 'Area determines Fire NOC requirements (state thresholds typically >500 sq ft), BOCW levy (if recently constructed), and SPCB category.',
    type: 'single_choice',
    options: [
      { value: 'lt_500sqft',       label: 'Less than 500 sq ft (very small)' },
      { value: '500_2000sqft',     label: '500 to 2,000 sq ft' },
      { value: '2000_10000sqft',   label: '2,000 to 10,000 sq ft' },
      { value: 'gt_10000sqft',     label: 'More than 10,000 sq ft' },
    ],
    weight: 4,
    complianceArea: 'peso_fire',
    source: 'Research §3, State Fire Act',
    gapTemplate: {
      finding: 'Premises area not confirmed — Fire NOC applicability unverified.',
      recommendation: 'Obtain Fire NOC from State Fire Services if premises exceed state threshold.',
      timeline: '90_days',
      penaltyExposure: 'Sealing + Rs.10,000 to Rs.1 lakh (state-variable) for operating without Fire NOC',
    },
    compliantAnswers: ['lt_500sqft', '500_2000sqft', '2000_10000sqft', 'gt_10000sqft'],
    appliesWhen: always,
  },
  {
    id: 'AD_APP_017',
    phase: 1,
    text: 'Which of the following equipment / installations does your dealership have?',
    helpText: 'Lifts and hoists require annual Competent Person inspection under Factories Act. CNG dispensers and paint booths have PESO and ATEX (explosion-proof) requirements. EV chargers need CEIG approval.',
    type: 'single_choice',
    options: [
      { value: 'lifts_hoists',  label: 'Vehicle lifts / two-post or four-post hoists' },
      { value: 'paint_booth',   label: 'Spray-painting booth' },
      { value: 'cng_dispenser', label: 'CNG dispenser / LPG storage' },
      { value: 'ev_charger',    label: 'EV charging station (AC/DC fast charger)' },
      { value: 'multiple',      label: 'Multiple of the above' },
      { value: 'none',          label: 'None of the above' },
    ],
    weight: 6,
    complianceArea: 'factories_osh',
    source: 'Research §3, Factories Act §28, PESO SMPV Rules 2016',
    gapTemplate: {
      finding: 'Specialised equipment identified — safety certification status unverified.',
      recommendation: 'Schedule annual Competent Person inspection for lifts/hoists; verify PESO licence for CNG; obtain CEIG NOC for EV charger.',
      timeline: '90_days',
      penaltyExposure: 'Factories Act: up to Rs.5 lakh; PESO: up to Rs.50,000 + closure',
    },
    compliantAnswers: ['lifts_hoists', 'paint_booth', 'cng_dispenser', 'ev_charger', 'multiple', 'none'],
    appliesWhen: always,
  },
  {
    id: 'AD_APP_018',
    phase: 1,
    text: 'How many litres of diesel or petrol do you store on-site (e.g., for test drives, generator, service operations)?',
    helpText: 'Storage <= 2,500 L requires only intimation to district authority. >2,500 L up to 25,000 L requires Form XIV licence. >25,000 L requires Form XV licence from PESO. All storage must comply with OISD-116.',
    type: 'single_choice',
    options: [
      { value: '0',              label: 'None — no fuel stored on-site' },
      { value: 'lt_2500',        label: 'Up to 2,500 litres (intimation only)' },
      { value: '2500_5000',      label: '2,501 to 5,000 litres (Form XIV licence)' },
      { value: '5000_25000',     label: '5,001 to 25,000 litres (Form XIV licence)' },
      { value: 'gt_25000',       label: 'More than 25,000 litres (Form XV licence)' },
    ],
    weight: 8,
    complianceArea: 'peso_fire',
    source: 'Research §3, Petroleum Act 1934, Petroleum Rules 2002',
    gapTemplate: {
      finding: 'Diesel/petrol stored on-site — PESO licence status unverified.',
      recommendation: 'Obtain Form XIV/XV licence from PESO if applicable. Ensure storage area meets OISD-116 separation distances.',
      timeline: '90_days',
      penaltyExposure: 'Up to Rs.50,000 + closure under Petroleum Act §23',
    },
    compliantAnswers: ['0', 'lt_2500', '2500_5000', '5000_25000', 'gt_25000'],
    appliesWhen: always,
  },
  {
    id: 'AD_APP_019',
    phase: 1,
    text: 'Are your business premises owned or leased?',
    helpText: 'Leased premises require a registered lease deed to claim GST ITC on rent. An unregistered lease deed is inadmissible as evidence and may create title disputes.',
    type: 'single_choice',
    options: [
      { value: 'owned',    label: 'Owned (or owned by promoter)' },
      { value: 'leased',   label: 'Leased / rented from third party' },
      { value: 'mixed',    label: 'Some owned, some leased' },
    ],
    weight: 4,
    complianceArea: 'lease',
    source: 'Research §3, Registration Act 1908',
    gapTemplate: {
      finding: 'Leased premises — registration status of lease deed unverified.',
      recommendation: 'Register all leases >=12 months with Sub-Registrar. Ensure stamp duty paid.',
      timeline: '90_days',
      penaltyExposure: 'Unregistered lease void as evidence; stamp duty arrears + penalty up to 10x stamp duty',
    },
    compliantAnswers: ['owned', 'leased', 'mixed'],
    appliesWhen: always,
  },

  // --------------------------------------------------------------------------
  // Workforce Composition
  // --------------------------------------------------------------------------
  {
    id: 'AD_APP_020',
    phase: 1,
    text: 'Do you engage contract labour (e.g., vehicle washers, security, canteen, valet)? If yes, approximately how many?',
    helpText: 'Contract Labour (R&A) Act applies when the principal employer (dealership) has >=20 contract workers. Contractors with >=50 workers need their own licence. Contract workers must be covered for EPF/ESI.',
    type: 'single_choice',
    options: [
      { value: 'no',       label: 'No — all workers are on direct rolls' },
      { value: 'lt_20',    label: 'Yes — fewer than 20 contract workers' },
      { value: '20_49',    label: 'Yes — 20 to 49 contract workers' },
      { value: 'gte_50',   label: 'Yes — 50 or more contract workers' },
    ],
    weight: 7,
    complianceArea: 'contract_labour',
    source: 'Research §3, Contract Labour (R&A) Act 1970',
    gapTemplate: {
      finding: 'Contract labour engaged — Registration Certificate and contractor compliance unverified.',
      recommendation: 'Obtain RC from Labour Commissioner; verify each contractor\'s CL Licence; ensure wages, EPF/ESI deposited.',
      timeline: '30_days',
      penaltyExposure: 'Rs.500 to Rs.1,000 per default + inspector action; denial of contract work',
    },
    compliantAnswers: ['no', 'lt_20', '20_49', 'gte_50'],
    appliesWhen: always,
  },
  {
    id: 'AD_APP_021',
    phase: 1,
    text: 'Do you employ apprentices under the Apprentices Act 1961?',
    helpText: 'Dealerships with >=4 workers in prescribed trades (mechanic, electrician, welder, painter) must engage apprentices as per quota. Apprentice wages are exempt from PF/ESI but stipend minimums apply.',
    type: 'yes_no',
    weight: 4,
    complianceArea: 'wages',
    source: 'Research §3, Apprentices Act 1961 §3',
    gapTemplate: {
      finding: 'Apprentices employed — Apprentices Act obligations unverified.',
      recommendation: 'Register apprenticeship contracts on NAPS portal; ensure stipend meets minimum; file Form P-II returns.',
      timeline: '30_days',
      penaltyExposure: 'Rs.500 to Rs.1,000 per quarter per apprentice for non-compliance',
    },
    compliantAnswers: ['yes', 'no'],
    appliesWhen: always,
  },
  {
    id: 'AD_APP_022',
    phase: 1,
    text: 'Are any of your workers engaged in hazardous processes — such as spray-painting, welding, battery acid handling, or use of oxy-acetylene equipment?',
    helpText: 'Hazardous-process workers trigger additional OSH Code / Factories Act obligations: mandatory health exams, PPE provision, MSDS display, and higher penalty exposure (up to 2 years imprisonment). Paint-booth operators and welders typically qualify.',
    type: 'yes_no',
    weight: 9,
    complianceArea: 'factories_osh',
    source: 'Research §3, Factories Act §87, OSH Code Schedule',
    gapTemplate: {
      finding: 'Hazardous-process workers present — OSH Code / Factories Act obligations significantly elevated.',
      recommendation: 'Conduct annual medical examination; issue PPE; display MSDS; implement hot-work permit system.',
      timeline: '30_days',
      penaltyExposure: 'Up to Rs.5 lakh fine + 2 yr imprisonment for hazardous-process breach (Factories Act §92)',
    },
    compliantAnswers: ['yes', 'no'],
    appliesWhen: always,
  },

  // --------------------------------------------------------------------------
  // Cross-sell
  // --------------------------------------------------------------------------
  {
    id: 'AD_APP_023',
    phase: 1,
    text: 'Does your dealership sell motor insurance? If yes, do you operate as a MISP (Motor Insurance Service Provider) under one insurer or intermediary?',
    helpText: 'IRDAI mandates that dealers selling insurance must hold MISP appointment from one sponsor (insurer or intermediary). The 22.5%/19.5% MISP fee caps were withdrawn in 2023; distribution fees are now governed by the IRDAI EoM Regulations 2024 and the sponsor\'s Board-approved policy.',
    type: 'single_choice',
    options: [
      { value: 'no',         label: 'No — we do not facilitate motor insurance' },
      { value: 'yes_misp',   label: 'Yes — we hold a MISP appointment letter from one insurer/intermediary' },
      { value: 'yes_no_uin', label: 'Yes — we sell insurance but do not have a formal MISP UIN' },
    ],
    weight: 8,
    complianceArea: 'misp',
    source: 'Research §3, IRDAI MISP Guidelines 2017, IRDAI EoM Regulations 2024',
    gapTemplate: {
      finding: 'Insurance sold without confirmed MISP UIN — IRDAI compliance at risk.',
      recommendation: 'Obtain MISP appointment letter from one intermediary/insurer. Register UIN on IIB. Ensure Designated Person holds POS certificate.',
      timeline: '30_days',
      penaltyExposure: 'MISP cancellation + insurer penalty up to Rs.1 crore u/s 102 Insurance Act',
    },
    compliantAnswers: ['no', 'yes_misp'],
    partiallyCompliantAnswers: ['yes_no_uin'],
    appliesWhen: always,
  },
  {
    id: 'AD_APP_024',
    phase: 1,
    text: 'Does your dealership facilitate vehicle finance for any bank / NBFC as a Direct Selling Agent (DSA)?',
    helpText: 'DSA activities are governed by RBI\'s Master Direction on Outsourcing of Financial Services 2023. Key obligations: KYC per lender SOP, Fair Practice Code display, no sub-DSA without lender consent.',
    type: 'yes_no',
    weight: 6,
    complianceArea: 'dsa',
    source: 'Research §3, RBI Master Direction on Outsourcing 2023',
    gapTemplate: {
      finding: 'DSA activity confirmed — RBI outsourcing compliance unverified.',
      recommendation: 'Ensure DSA agreements are current; display Fair Practice Code; no retention of Aadhaar copies beyond KYC purpose.',
      timeline: '30_days',
      penaltyExposure: 'Lender-level regulatory action; possible cancellation of DSA arrangement',
    },
    compliantAnswers: ['yes', 'no'],
    appliesWhen: always,
  },
  {
    id: 'AD_APP_025',
    phase: 1,
    text: 'Does your dealership collect and process personal data of customers in digital form (e.g., via DMS, CRM, telematics, loan applications, test-drive forms)?',
    helpText: 'Any dealership using a Dealer Management System (DMS), CRM software, or capturing customer KYC digitally is a "Data Fiduciary" under the DPDP Act 2023. Substantive obligations begin 13 May 2027, but privacy notice and consent architecture should be built now.',
    type: 'yes_no',
    weight: 7,
    complianceArea: 'dpdp',
    source: 'Research §3, DPDP Act 2023 §2(i), DPDP Rules 2025 (gazette 14 Nov 2025)',
    gapTemplate: {
      finding: 'Personal data processed — DPDP Act 2023 obligations apply (substantive from 13 May 2027).',
      recommendation: 'Issue privacy notice in prescribed format; implement purpose-specific consent; map all customer data flows (KYC, finance, RTO, telematics).',
      timeline: 'prepare_by_2027',
      penaltyExposure: 'Up to Rs.250 crore (security safeguards), Rs.200 crore (breach notification), Rs.50 crore (other violations) — per-violation from 13 May 2027',
    },
    compliantAnswers: ['yes', 'no'],
    appliesWhen: always,
  },
]
