// ============================================================================
// Phase 5 — EPR & Circular Economy (~10 questions)
// Source: Research §4.6 (EPR subset), Battery Waste Management Rules 2022,
//         E-Waste Management Rules 2022, ELV Rules 2025 (eff. 1 Apr 2025),
//         Used Oil (HW Rules 2016)
// ============================================================================

import type { AutoDealerQuestion, ApplicabilityProfile } from '@/types/auto-dealer'

export const PHASE5_EPR_QUESTIONS: AutoDealerQuestion[] = [
  // --------------------------------------------------------------------------
  // Battery Waste Management Rules 2022
  // --------------------------------------------------------------------------
  {
    id: 'AD_P5_001',
    phase: 5,
    text: 'Is your dealership registered on the CPCB EPR portal for battery waste (if you import, manufacture, or sell batteries under your own brand)?',
    helpText: 'Battery Waste Management Rules 2022 impose EPR (Extended Producer Responsibility) on producers, importers, and brand owners of batteries including lead-acid automotive batteries. If you sell batteries under your own dealership brand (not OEM brand), you are a "producer" and must register on eprbattery.cpcb.gov.in.',
    type: 'yes_no',
    weight: 7,
    complianceArea: 'battery_waste',
    source: 'Research §4.6, Battery Waste Management Rules 2022, eprbattery.cpcb.gov.in',
    gapTemplate: {
      finding: 'Battery sales under own brand without CPCB EPR portal registration.',
      recommendation: 'Register on eprbattery.cpcb.gov.in as producer/importer; set annual collection targets; file quarterly EPR returns.',
      timeline: '30_days',
      penaltyExposure: 'Environmental Compensation per CPCB schedule; cancellation of registration; EC cumulative for each shortfall quarter',
    },
    compliantAnswers: ['yes', 'not_applicable'],
    appliesWhen: (_p: ApplicabilityProfile) => true,
  },
  {
    id: 'AD_P5_002',
    phase: 5,
    text: 'Are waste (used / end-of-life) lead-acid batteries from the workshop channelised exclusively to registered battery recyclers, and are quarterly returns filed on the CPCB EPR portal?',
    helpText: 'Used automotive batteries from workshop replacements are hazardous waste. They must be sold only to CPCB-registered lead-acid battery recyclers (not informal scrap dealers). Quarterly return on EPR portal required.',
    type: 'yes_no',
    weight: 8,
    complianceArea: 'battery_waste',
    source: 'Research §4.6, Battery Waste Management Rules 2022 Rule 6',
    gapTemplate: {
      finding: 'Used batteries not channelised to registered recyclers or EPR returns not filed.',
      recommendation: 'Identify CPCB-registered battery recyclers in your region; maintain collection register; file quarterly returns on CPCB EPR portal; keep Form 10 manifest for each consignment.',
      timeline: '30_days',
      penaltyExposure: 'Environmental Compensation per CPCB schedule; HW Rules 2016 action for improper disposal',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (p: ApplicabilityProfile) => p.hasWorkshop,
  },

  // --------------------------------------------------------------------------
  // E-Waste Management Rules 2022
  // --------------------------------------------------------------------------
  {
    id: 'AD_P5_003',
    phase: 5,
    text: 'Are e-waste items from the workshop (diagnostic scanners, ECUs, infotainment modules, PCBs, wiring harnesses) sent to an authorised e-waste dismantler registered with CPCB?',
    helpText: 'E-Waste Management Rules 2022 cover electrical and electronic waste generated by consumers and producers. Workshop e-waste (old ECUs, diagnostic tools, battery management systems) must be channelled to CPCB-authorised e-waste dismantlers, not scrap dealers.',
    type: 'yes_no',
    weight: 6,
    complianceArea: 'e_waste',
    source: 'Research §4.6, E-Waste Management Rules 2022 Rule 16',
    gapTemplate: {
      finding: 'Workshop e-waste not channelled to authorised dismantler.',
      recommendation: 'Identify CPCB-authorised e-waste dismantlers on cpcb.nic.in; establish annual e-waste channelisation agreement; maintain collection register; issue Waste Transfer Note.',
      timeline: '90_days',
      penaltyExposure: 'Environmental Compensation per CPCB schedule; registration cancellation for repeat violators',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (p: ApplicabilityProfile) => p.hasWorkshop,
  },

  // --------------------------------------------------------------------------
  // ELV Rules 2025 (eff. 1 Apr 2025)
  // Source: S.O. 98(E) dt. 6 Jan 2025; first producer declarations due 30 Apr 2026
  // --------------------------------------------------------------------------
  {
    id: 'AD_P5_004',
    phase: 5,
    text: 'Are all dealership demo, test-drive / test-ride, and retired fleet vehicles — once reaching end-of-life — routed exclusively to CPCB-registered Registered Vehicle Scrapping Facilities (RVSFs)?',
    helpText: 'ELV Rules 2025 (eff. 1 Apr 2025) prohibit dealing in any non-RVSF-scrapped vehicle. Dealer demo fleets and test-drive vehicles are subject to the mandatory RVSF channel on retirement. Selling ELV vehicles to informal scrap yards is illegal from 1 Apr 2025.',
    type: 'yes_no',
    weight: 8,
    complianceArea: 'elv',
    source: 'Research §4.6 / §6, ELV Rules 2025 S.O. 98(E) 6 Jan 2025',
    gapTemplate: {
      finding: 'Demo/test fleet vehicles not confirmed as routed to registered RVSFs.',
      recommendation: 'Identify nearest CPCB-registered RVSF (parivahan.gov.in/RVSF list); route all ELV demo vehicles there; obtain Certificate of Destruction (COD); maintain COD register.',
      timeline: '30_days',
      penaltyExposure: 'Rs.10 lakh to Rs.15 lakh per contravention; Rs.10 lakh continuing penalty; up to 3 yr imprisonment on default in payment (ELV Rules 2025)',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (_p: ApplicabilityProfile) => true,
  },
  {
    id: 'AD_P5_005',
    phase: 5,
    text: 'If your combined demo / test-drive / test-ride fleet exceeds 100 vehicles, have you registered as a Bulk Consumer on the CPCB ELV portal?',
    helpText: 'ELV Rules 2025 define entities with >100 vehicles as "Bulk Consumers" with enhanced EPR obligations, including annual producer declarations (Form 1) by 30 April and quarterly reports. First declaration due 30 Apr 2026 for FY 2025-26.',
    type: 'yes_no',
    weight: 7,
    complianceArea: 'elv',
    source: 'Research §4.6, ELV Rules 2025 §3 (Bulk Consumer definition)',
    gapTemplate: {
      finding: 'Fleet >100 vehicles but Bulk Consumer registration not confirmed.',
      recommendation: 'Register on CPCB ELV portal as Bulk Consumer; submit Form 1 annual declaration by 30 Apr; file quarterly reports; maintain Certificate of Destruction for each retired vehicle.',
      timeline: '30_days',
      penaltyExposure: 'Rs.10 lakh to Rs.15 lakh per contravention under ELV Rules 2025',
    },
    compliantAnswers: ['yes', 'not_applicable'],
    appliesWhen: (_p: ApplicabilityProfile) => true,
  },
  {
    id: 'AD_P5_006',
    phase: 5,
    text: 'Is used engine oil and coolant (generated in workshop) channelised to MoEFCC/CPCB-registered used-oil re-refiners and is the chain-of-custody manifest (Form 10) completed for every transfer?',
    helpText: 'Used oil is a hazardous waste under HW Rules 2016 and also an EPR-relevant material. Transfer to unregistered collectors is an offence. CPCB maintains a list of registered used-oil re-refiners. The Form 10 HW manifest accompanies each consignment.',
    type: 'yes_no',
    weight: 7,
    complianceArea: 'hazardous_waste',
    source: 'Research §4.6, HOWM Rules 2016 Rule 9',
    gapTemplate: {
      finding: 'Used oil not channelled to registered re-refiners or manifest not completed.',
      recommendation: 'Contract with a CPCB-listed used-oil re-refiner; complete Form 10 for every transfer; maintain consignment register; file Form 4 annual HW return by 30 Jun.',
      timeline: '30_days',
      penaltyExposure: 'Environmental Compensation Rs.1 lakh to Rs.1 crore under HW Rules; EPA closure under §5',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (p: ApplicabilityProfile) => p.hasWorkshop,
  },
  {
    id: 'AD_P5_007',
    phase: 5,
    text: 'Is any plastic packaging waste generated from new vehicle shipments (protective wrapping, polystyrene, stretch film) managed under the Plastic Waste Management Rules as a bulk generator?',
    helpText: 'Dealers receive vehicles wrapped in plastic protective packaging. Under PWM Rules 2016 (amended 2022), a bulk generator (premises generating >100 kg/day plastic waste) must register with the local body and submit annual returns.',
    type: 'yes_no',
    weight: 4,
    complianceArea: 'e_waste',
    source: 'Research §4.6, Plastic Waste Management Rules 2016 (Amdt 2022)',
    gapTemplate: {
      finding: 'Plastic packaging waste not managed under PWM Rules bulk-generator obligations.',
      recommendation: 'Estimate monthly plastic waste quantity; register with local ULB if >100 kg/day; channel plastic waste to registered recyclers; submit annual returns to ULB.',
      timeline: '90_days',
      penaltyExposure: 'Environmental Compensation; local-body action',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (_p: ApplicabilityProfile) => true,
  },
  {
    id: 'AD_P5_008',
    phase: 5,
    text: 'For EV batteries reaching end of life in the workshop — is a separate battery waste collection and disposal process in place per Battery Waste Management (Amendment) Rules 2025?',
    helpText: 'Battery Waste Management (Amendment) Rules 2025 (24 Feb 2025) introduced additional requirements for lithium-ion EV battery disposal: separate storage, certified dismantling, and quarterly EPR returns. EV dealers and workshops are directly impacted.',
    type: 'yes_no',
    weight: 6,
    complianceArea: 'battery_waste',
    source: 'Research §6, Battery Waste Management (Amendment) Rules 2025 (24 Feb 2025)',
    gapTemplate: {
      finding: 'EV battery end-of-life process not in compliance with 2025 Amendment Rules.',
      recommendation: 'Set up separate EV battery storage (non-flammable, ventilated); contract with CPCB-registered Li-ion battery recycler; file quarterly EPR returns; update HW authorisation to include Li-ion.',
      timeline: '90_days',
      penaltyExposure: 'Environmental Compensation per CPCB schedule; SPCB closure for improper storage of Li-ion batteries',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (p: ApplicabilityProfile) =>
      ['ev_only', 'both_2w_4w', 'mixed'].includes(p.vehicleType) && p.hasWorkshop,
  },
  {
    id: 'AD_P5_009',
    phase: 5,
    text: 'Is the Form 4 Hazardous Waste Annual Return filed with the SPCB by 30 June each year, covering all waste categories generated in the workshop?',
    helpText: 'HW Rules 2016 Form 4 must be filed annually by 30 June. The return covers all HW categories: used oil, paint sludge, solvent waste, coolant, battery acid, HW-contaminated rags/PPE. Many dealers file for used oil only and miss other categories.',
    type: 'yes_no',
    weight: 7,
    complianceArea: 'hazardous_waste',
    source: 'Research §4.6, HOWM Rules 2016 Rule 7',
    gapTemplate: {
      finding: 'HW Form 4 annual return not filed by 30 June or incomplete categories.',
      recommendation: 'Compile full HW inventory (all categories); file Form 4 by 30 Jun; include quantities generated, stored, transferred, and disposed. Late filing attracts EC.',
      timeline: '30_days',
      penaltyExposure: 'Environmental Compensation per CPCB schedule; SPCB CTO renewal risk',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (p: ApplicabilityProfile) => p.hasWorkshop,
  },
  {
    id: 'AD_P5_010',
    phase: 5,
    text: 'Have you assessed your dealership\'s obligation as an ELV "Producer" under ELV Rules 2025 and filed Form 1 (Annual Producer Declaration) for FY 2025-26 by 30 April 2026?',
    helpText: 'Under ELV Rules 2025 (eff. 1 Apr 2025), all vehicle manufacturers and authorised dealers who sell new vehicles are "Producers" with EPR obligations. The first annual declaration (Form 1) is due 30 April 2026 for FY 2025-26 (vehicles sold between 1 Apr 2025 and 31 Mar 2026).',
    type: 'yes_no',
    weight: 7,
    complianceArea: 'elv',
    source: 'Research §6, ELV Rules 2025 S.O. 98(E), parivahan.gov.in ELV portal',
    gapTemplate: {
      finding: 'ELV producer status not assessed or Form 1 declaration not filed for FY 2025-26.',
      recommendation: 'Register on MoRTH / CPCB ELV portal as Producer; compute units sold in FY 2025-26; file Form 1 by 30 Apr 2026; set up annual reminder.',
      timeline: '30_days',
      penaltyExposure: 'Rs.10 lakh to Rs.15 lakh per contravention + continuing penalty under ELV Rules 2025',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (_p: ApplicabilityProfile) => true,
  },
]
