// ============================================================================
// Phase 2 — Generic Statutory Compliance (~30 questions)
// Source: Research §4.2 Labour Codes/EPF/ESI/S&E, §4.5 POSH,
//         §4.8 GST/TCS (partial), §4.13 Companies Act (partial)
// Defaults to new Labour Codes regime; legacy-specific questions
// are gated by p.labourRegime === 'legacy'.
// ============================================================================

import type { AutoDealerQuestion, ApplicabilityProfile } from '@/types/auto-dealer'
import { employeeGte, operatesInPTState, turnoverGte } from './rules-engine'

export const PHASE2_STATUTORY_QUESTIONS: AutoDealerQuestion[] = [
  // --------------------------------------------------------------------------
  // Wages & Appointment (Code on Wages — new regime)
  // --------------------------------------------------------------------------
  {
    id: 'AD_P2_001',
    phase: 2,
    text: 'Are appointment letters issued in writing to ALL workers, including contract staff and apprentices?',
    helpText: 'Under Code on Wages 2019, appointment letters are mandatory for all workers. Penalty for non-issuance: up to Rs.50,000 per default under Occupational Safety Code.',
    type: 'yes_no',
    weight: 8,
    complianceArea: 'wages',
    source: 'Research §4.2, Code on Wages 2019 §3',
    gapTemplate: {
      finding: 'Appointment letters not issued to all workers — Code on Wages violation.',
      recommendation: 'Issue appointment letters to all employees (permanent, fixed-term, contract, apprentice) stating wages, terms, and designation. Use bilingual format where required by state.',
      timeline: '30_days',
      penaltyExposure: 'Up to Rs.50,000 per default; further Rs.1,000/day for continuing default',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (p: ApplicabilityProfile) => employeeGte(p, 1),
  },
  {
    id: 'AD_P2_002',
    phase: 2,
    text: 'Are wages paid to all workers by the 7th of the following month via bank transfer or digital payment?',
    helpText: 'Code on Wages 2019 requires wages to be paid within 7 days (establishments with <1,000 workers) via bank/digital. Cash payments attract additional scrutiny.',
    type: 'yes_no',
    weight: 8,
    complianceArea: 'wages',
    source: 'Research §4.2, Code on Wages 2019 §17',
    gapTemplate: {
      finding: 'Wages not paid within statutory timeline or via non-compliant mode.',
      recommendation: 'Configure payroll to credit all wages by 7th of month. Maintain Form X wage register electronically.',
      timeline: '30_days',
      penaltyExposure: 'Up to Rs.50,000 per default; delayed wages attract interest at prescribed rate',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (p: ApplicabilityProfile) => employeeGte(p, 1),
  },
  {
    id: 'AD_P2_003',
    phase: 2,
    text: 'Is the wage structure designed so that allowances (HRA, conveyance, etc.) do not exceed 50% of the total wage?',
    helpText: 'Under the new Labour Codes "wages" definition, allowances exceeding 50% of total wage are counted as "wages" for PF/gratuity/bonus calculations — increasing liability. A structure where basic <=50% inflates statutory costs significantly.',
    type: 'yes_no',
    weight: 7,
    complianceArea: 'wages',
    source: 'Research §4.2, Code on Wages 2019 §2(y)',
    gapTemplate: {
      finding: 'Wage structure may have allowances >50% — inflated PF/gratuity/bonus liability risk.',
      recommendation: 'Review salary structure with HR/CA; restructure to ensure basic + DA >= 50% of CTC; recalculate PF, gratuity, and bonus base.',
      timeline: '90_days',
      penaltyExposure: 'Underdeposit of PF/ESI: 12% interest + 5-25% damages; potential criminal action',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (p: ApplicabilityProfile) => employeeGte(p, 1),
  },
  {
    id: 'AD_P2_004',
    phase: 2,
    text: 'Are minimum wages paid as per the applicable schedule — workshop/technicians (manufacturing schedule) and showroom/admin (S&E/commercial schedule) — with latest VDA adjustment?',
    helpText: 'Auto dealerships straddle two minimum-wage schedules: technicians are on the "engineering/automobile" or "manufacturing" schedule; sales/admin are on the "commercial establishments/S&E" schedule. Variable Dearness Allowance (VDA) is revised semi-annually.',
    type: 'yes_no',
    weight: 7,
    complianceArea: 'wages',
    source: 'Research §4.2, Minimum Wages Act 1948 / Code on Wages 2019',
    gapTemplate: {
      finding: 'Minimum wages may not be aligned to current rates including latest VDA revision.',
      recommendation: 'Check state labour department portal for latest minimum wages (revised semi-annually). Maintain Form X with current rates. Arrears, if any, must be paid within 3 years.',
      timeline: '30_days',
      penaltyExposure: 'Rs.500 per default (Minimum Wages Act); repeat = Rs.1,000; imprisonment up to 6 months',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (p: ApplicabilityProfile) => employeeGte(p, 1),
  },

  // --------------------------------------------------------------------------
  // EPF
  // --------------------------------------------------------------------------
  {
    id: 'AD_P2_005',
    phase: 2,
    text: 'Is your dealership registered with EPFO and have you allotted Universal Account Numbers (UANs) to all eligible employees?',
    helpText: 'EPF applies to establishments with >=20 employees. Registration must be done within one month of crossing the threshold. UANs must be generated for all employees earning up to Rs.15,000/month (basic + DA).',
    type: 'yes_no',
    weight: 9,
    complianceArea: 'epf',
    source: 'Research §4.2, EPF Act 1952 §1(3)',
    gapTemplate: {
      finding: 'EPF registration or UAN allotment incomplete — EPFO non-compliance.',
      recommendation: 'Register on EPFO Unified Portal immediately; obtain Establishment Code; submit Form 5A; allot UANs to all eligible workers.',
      timeline: '30_days',
      penaltyExposure: '12% interest p.a. + 5-25% damages u/s 14B EPF Act; criminal action for diverted contributions',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (p: ApplicabilityProfile) => employeeGte(p, 20),
  },
  {
    id: 'AD_P2_006',
    phase: 2,
    text: 'Are EPF contributions (employee 12% + employer 12%) deposited by the 15th of every month and ECR filed on time?',
    helpText: 'ECR (Electronic Challan cum Return) must be filed and payment made by 15th of following month. Even one-day delay attracts interest. Ensure demo-fleet technicians and washers are included.',
    type: 'yes_no',
    weight: 8,
    complianceArea: 'epf',
    source: 'Research §4.2, EPF Scheme 1952 Para 38',
    gapTemplate: {
      finding: 'EPF contributions not consistently deposited by 15th.',
      recommendation: 'Set up auto-debit for EPF challan by 12th of month. Reconcile ECR with payroll monthly. Clear all arrears immediately.',
      timeline: '30_days',
      penaltyExposure: '12% interest p.a. on delayed deposits + damages up to 100% of arrears u/s 14B',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (p: ApplicabilityProfile) => employeeGte(p, 20),
  },

  // --------------------------------------------------------------------------
  // ESI
  // --------------------------------------------------------------------------
  {
    id: 'AD_P2_007',
    phase: 2,
    text: 'Is your dealership registered under the ESI Act and are all eligible workers (earning <=Rs.21,000/month gross) covered, including technicians, washers, and security?',
    helpText: 'ESI applies to factories and shops with >=10 employees in notified areas. Wage ceiling is Rs.21,000/month (Rs.25,000 for PWD). Workshop technicians and washers are frequently omitted — this is the most common ESI audit finding at dealerships.',
    type: 'yes_no',
    weight: 9,
    complianceArea: 'esi',
    source: 'Research §4.2, ESI Act 1948 §2A',
    gapTemplate: {
      finding: 'ESI registration incomplete or eligible workers (esp. technicians) excluded.',
      recommendation: 'Register on ESIC portal; obtain 17-digit Employer Code; generate IP numbers for all eligible workers. Retrospective coverage may be required.',
      timeline: '30_days',
      penaltyExposure: 'Twice the contribution amount as penalty + 12% interest p.a.; retrospective liability for up to 5 years',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (p: ApplicabilityProfile) => employeeGte(p, 10),
  },
  {
    id: 'AD_P2_008',
    phase: 2,
    text: 'Are ESI contributions (employee 0.75% + employer 3.25%) deposited by the 15th and half-yearly Form 6 returns filed by 11 May and 11 November?',
    helpText: 'ESI contribution rate: employer 3.25% + employee 0.75% = 4% of gross wages. Form 6 (half-yearly return) is filed twice yearly.',
    type: 'yes_no',
    weight: 7,
    complianceArea: 'esi',
    source: 'Research §4.2, ESI Act 1948 §39(5)',
    gapTemplate: {
      finding: 'ESI contributions not deposited by 15th or Form 6 return overdue.',
      recommendation: 'Configure payroll to calculate ESI correctly; file Form 6 returns by 11 May and 11 Nov; clear arrears with 12% interest.',
      timeline: '30_days',
      penaltyExposure: '12% interest + damages up to 25% for delayed payment; Rs.5,000 fine for return default',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (p: ApplicabilityProfile) => employeeGte(p, 10),
  },

  // --------------------------------------------------------------------------
  // Professional Tax
  // --------------------------------------------------------------------------
  {
    id: 'AD_P2_009',
    phase: 2,
    text: 'Are PTRC (Professional Tax Registration Certificate) and PTEC (Enrolment Certificate for proprietor/partners/directors) live and in good standing in every PT-applicable state you operate in?',
    helpText: 'Professional Tax applies in Maharashtra, Karnataka, West Bengal, Tamil Nadu, AP, Telangana, Gujarat, Odisha, Assam, and several smaller states. Karnataka raised exemption to Rs.25,000/month w.e.f. 1 Apr 2025.',
    type: 'yes_no',
    weight: 7,
    complianceArea: 'professional_tax',
    source: 'Research §4.2, state PT Acts (e.g. MVAT Act MH, KPT Act KA)',
    gapTemplate: {
      finding: 'PTRC / PTEC not confirmed in all PT-applicable states.',
      recommendation: 'Apply for PTRC and PTEC on state commercial tax / labour portal in each applicable state. Display certificate at premises.',
      timeline: '30_days',
      penaltyExposure: 'Maharashtra: Rs.5/day; Karnataka: Rs.100/month; other states vary',
    },
    compliantAnswers: ['yes'],
    appliesWhen: operatesInPTState,
  },
  {
    id: 'AD_P2_010',
    phase: 2,
    text: 'Is Professional Tax deducted from employees\' salaries per state slab and deposited by the due date (Maharashtra: 30th; Karnataka: 20th; others vary)?',
    helpText: 'PT slabs and due dates differ by state. Failure to deduct and deposit attracts interest (1-2% per month) plus state-specific penalties.',
    type: 'yes_no',
    weight: 6,
    complianceArea: 'professional_tax',
    source: 'Research §4.2, state PT Rules',
    gapTemplate: {
      finding: 'PT deduction and deposit may be non-compliant or untimely.',
      recommendation: 'Configure payroll software with current PT slabs for each state; automate deposit by due date; file annual PT return (Form IIIB in MH) by 31 May.',
      timeline: '30_days',
      penaltyExposure: 'Interest 1-2% per month + state penalty on arrears',
    },
    compliantAnswers: ['yes'],
    appliesWhen: operatesInPTState,
  },

  // --------------------------------------------------------------------------
  // POSH
  // --------------------------------------------------------------------------
  {
    id: 'AD_P2_011',
    phase: 2,
    text: 'Has an Internal Committee (IC) been constituted under POSH Act 2013 with at least one external member, and has it been reconstituted within 3 years of the previous term?',
    helpText: 'Every employer with >=10 employees must constitute an IC. The external member must be from an NGO, association committed to women\'s welfare, or a qualified individual. Term is 3 years.',
    type: 'yes_no',
    weight: 9,
    complianceArea: 'posh',
    source: 'Research §4.5, POSH Act 2013 §4',
    gapTemplate: {
      finding: 'IC not constituted or term expired — critical POSH non-compliance.',
      recommendation: 'Constitute IC immediately with Presiding Officer (senior woman employee), 2+ members committed to women\'s causes, and 1 external member. Issue constitution order with signatures.',
      timeline: '30_days',
      penaltyExposure: 'Rs.50,000 fine; cancellation of business registration on repeat (POSH Act §26)',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (p: ApplicabilityProfile) => employeeGte(p, 10),
  },
  {
    id: 'AD_P2_012',
    phase: 2,
    text: 'Has POSH awareness training been conducted for all employees (including contract workers) in the last 12 months?',
    helpText: 'Training must cover the definition of sexual harassment, complaint mechanism, and IC contact. Conduct separate sessions for the male-dominant workshop floor. At least one session per year is the minimum; workshops benefit from quarterly toolbox talks.',
    type: 'yes_no',
    weight: 6,
    complianceArea: 'posh',
    source: 'Research §4.5, POSH Act 2013 §19(b)',
    gapTemplate: {
      finding: 'Annual POSH training not conducted for all workers.',
      recommendation: 'Schedule POSH training within 30 days; include workshop and contract staff; maintain attendance register as evidence.',
      timeline: '30_days',
      penaltyExposure: 'Rs.50,000 fine for non-compliance with employee-awareness obligations',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (p: ApplicabilityProfile) => employeeGte(p, 10),
  },
  {
    id: 'AD_P2_013',
    phase: 2,
    text: 'Has the IC\'s annual report been submitted to the District Officer by 31 January, and is the POSH policy displayed in the vernacular at every outlet?',
    helpText: 'The IC must prepare and submit an annual report to the District Officer under Rule 14 of POSH Rules 2013. The policy must be displayed prominently in the language(s) understood by most employees at each outlet.',
    type: 'yes_no',
    weight: 7,
    complianceArea: 'posh',
    source: 'Research §4.5, POSH Rules 2013 Rule 14',
    gapTemplate: {
      finding: 'Annual POSH report not submitted or policy not displayed in vernacular.',
      recommendation: 'Prepare and submit IC annual report to District Officer by 31 Jan each year. Display policy in Hindi and local language at all outlets.',
      timeline: '30_days',
      penaltyExposure: 'Rs.50,000 fine for non-submission; cancellation on repeat',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (p: ApplicabilityProfile) => employeeGte(p, 10),
  },

  // --------------------------------------------------------------------------
  // Bonus & Gratuity
  // --------------------------------------------------------------------------
  {
    id: 'AD_P2_014',
    phase: 2,
    text: 'Is statutory bonus of at least 8.33% paid to all eligible employees (basic+DA <=Rs.21,000/month, worked >=30 days) by 30 November for March year-end?',
    helpText: 'Payment of Bonus Act applies to establishments with >=20 employees (>=10 under OSH Code). Eligible employees: earning basic+DA <=Rs.21,000/month. Minimum bonus: 8.33% of salary or Rs.100, whichever higher.',
    type: 'yes_no',
    weight: 7,
    complianceArea: 'bonus',
    source: 'Research §4.2, Payment of Bonus Act 1965 §10',
    gapTemplate: {
      finding: 'Statutory bonus not confirmed as paid by statutory deadline.',
      recommendation: 'Calculate allocable surplus; pay minimum 8.33% bonus by 30 Nov (March YE); maintain Form A, B, C, D registers; submit Form D to Labour Commissioner by 31 Jan.',
      timeline: '30_days',
      penaltyExposure: 'Imprisonment up to 6 months and/or fine up to Rs.1,000 per default',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (p: ApplicabilityProfile) => employeeGte(p, 20),
  },
  {
    id: 'AD_P2_015',
    phase: 2,
    text: 'Are gratuity payouts made within 30 days of cessation of employment, and is the gratuity liability provisioned in books?',
    helpText: 'Payment of Gratuity Act applies to establishments with >=10 employees (once applied, continues even if count falls below 10). Gratuity: 15 days wages per year of service, payable after 5 years continuous service. Maximum: Rs.20 lakh.',
    type: 'yes_no',
    weight: 7,
    complianceArea: 'gratuity',
    source: 'Research §4.2, Payment of Gratuity Act 1972 §4',
    gapTemplate: {
      finding: 'Gratuity payouts delayed beyond 30 days or liability not provisioned.',
      recommendation: 'Calculate gratuity liability immediately (15 x last drawn salary x years / 26); provision in annual accounts; consider LIC Group Gratuity scheme for funding.',
      timeline: '30_days',
      penaltyExposure: 'Simple interest at 10% p.a. from due date; up to 6 months imprisonment for wilful default',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (p: ApplicabilityProfile) => employeeGte(p, 10),
  },

  // --------------------------------------------------------------------------
  // Shops & Establishments
  // --------------------------------------------------------------------------
  {
    id: 'AD_P2_016',
    phase: 2,
    text: 'Is the Shops & Establishments registration live for every showroom and outlet, with weekly-off provision, holiday list, and women-employee closing-time provisions complied with?',
    helpText: 'Every showroom is a "shop / commercial establishment" under state S&E Acts. Registration must be obtained within 30 days of commencement. Women employees may not be employed after the closing time specified by the state (e.g., 21:30 in MH, 20:00 in KA).',
    type: 'yes_no',
    weight: 7,
    complianceArea: 's_and_e',
    source: 'Research §4.2, state S&E Acts',
    gapTemplate: {
      finding: 'S&E registration not confirmed or women-employee provisions non-compliant.',
      recommendation: 'Obtain S&E registration for each outlet within 30 days of commencement; display registration certificate; ensure women not deployed beyond state closing time without adequate safety.',
      timeline: '30_days',
      penaltyExposure: 'Rs.1,000 to Rs.10,000 per outlet per default; prosecution by labour inspector',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (_p: ApplicabilityProfile) => true,
  },
  {
    id: 'AD_P2_017',
    phase: 2,
    text: 'Are annual health check-ups provided to all workers aged 40 years or above?',
    helpText: 'Under OSH Code 2020, employers must provide annual health check-ups to workers >=40 years. This is a new requirement (New Labour Code regime) that most SME dealerships miss.',
    type: 'yes_no',
    weight: 5,
    complianceArea: 'wages',
    source: 'Research §4.2, OSH Code 2020 §28',
    gapTemplate: {
      finding: 'Annual health check-ups not provided to workers >=40 years.',
      recommendation: 'Tie up with a local hospital or diagnostic centre for annual health check-ups; maintain records; this applies to showroom and workshop staff.',
      timeline: '90_days',
      penaltyExposure: 'Rs.2 lakh fine under OSH Code for each default in health/safety obligation',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (p: ApplicabilityProfile) => p.labourRegime === 'new' && employeeGte(p, 10),
  },

  // --------------------------------------------------------------------------
  // GST
  // --------------------------------------------------------------------------
  {
    id: 'AD_P2_018',
    phase: 2,
    text: 'Are you registered for GST in every state of supply, and have you activated e-invoicing if your Aggregate Annual Turnover (AATO) exceeds Rs.5 crore?',
    helpText: 'E-invoicing is mandatory for AATO >Rs.5 crore since 1 Aug 2023. Each state supply requires a separate GSTIN. Multi-state dealers with a single GSTIN for all states are non-compliant.',
    type: 'yes_no',
    weight: 9,
    complianceArea: 'gst',
    source: 'Research §4.8, CGST Act §31A',
    gapTemplate: {
      finding: 'GST registration missing in one or more states of supply, or e-invoicing not activated.',
      recommendation: 'Register GST in every state of supply via GST portal. Activate e-invoice system (IRP) if AATO >Rs.5 cr. Ensure all vehicle invoices flow through IRP.',
      timeline: '30_days',
      penaltyExposure: 'Rs.10,000 per supply or 10% of tax, whichever higher; cancellation of GSTIN on persistent default',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (_p: ApplicabilityProfile) => true,
  },
  // L5: split into two questions — one for 4W-only dealers, one for 2W/mixed dealers
  {
    id: 'AD_P2_019',
    phase: 2,
    text: 'Are GST 2.0 rates applied correctly on vehicle invoices since 22 September 2025 (18% small cars; 28%+12% cess mid/large cars; 5% EVs)?',
    helpText: 'GST 2.0 effective 22 Sep 2025. Key rates for 4W dealers: small passenger cars (18%), mid/large cars (40% = 28%+12% cess), EVs (5%), auto parts (18%). FADA litigation on transitional cess credit is ongoing.',
    type: 'yes_no',
    weight: 8,
    complianceArea: 'gst',
    source: 'Research §4.8 / §6, PIB PRID 2164587 (22 Sep 2025)',
    gapTemplate: {
      finding: 'GST 2.0 rates may not be applied correctly on vehicle invoices.',
      recommendation: 'Update DMS/invoicing software to GST 2.0 rates with effect from 22 Sep 2025. Verify transitional cess credit position with CA. Refer gst_rates_by_hsn table for current rates.',
      timeline: '30_days',
      penaltyExposure: 'GST shortfall demand u/s 73/74: penalty up to 100% of tax; interest at 18% p.a.',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (p: ApplicabilityProfile) => p.vehicleType === '4w_only',
  },
  {
    id: 'AD_P2_019B',
    phase: 2,
    text: 'Are GST 2.0 rates applied correctly on vehicle invoices since 22 September 2025 (2W <=350cc: 18%; 2W >350cc: 28%+12% cess; small cars: 18%; EVs: 5%)?',
    helpText: 'GST 2.0 effective 22 Sep 2025. Key rates: 2-Wheeler <=350cc (18%), 2-Wheeler >350cc (40% = 28%+12% cess), small passenger cars (18%), mid/large cars (40%), EVs (5%), auto parts (18%). FADA litigation on transitional cess credit is ongoing.',
    type: 'yes_no',
    weight: 8,
    complianceArea: 'gst',
    source: 'Research §4.8 / §6, PIB PRID 2164587 (22 Sep 2025)',
    gapTemplate: {
      finding: 'GST 2.0 rates may not be applied correctly on vehicle invoices.',
      recommendation: 'Update DMS/invoicing software to GST 2.0 rates with effect from 22 Sep 2025. Verify transitional cess credit position with CA. Refer gst_rates_by_hsn table for current rates.',
      timeline: '30_days',
      penaltyExposure: 'GST shortfall demand u/s 73/74: penalty up to 100% of tax; interest at 18% p.a.',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (p: ApplicabilityProfile) => p.vehicleType !== '4w_only',
  },
  {
    id: 'AD_P2_020',
    phase: 2,
    text: 'Are GSTR-1, GSTR-3B, GSTR-9, and GSTR-9C filed within due dates for the last 12 months?',
    helpText: 'Common defaults at dealerships: GSTR-9 (annual reconciliation) filed late; GSTR-9C (reconciliation statement) not filed where AATO >Rs.5 crore. Demo-car ITC position should be documented.',
    type: 'yes_no',
    weight: 7,
    complianceArea: 'gst',
    source: 'Research §4.8, CGST Act §44',
    gapTemplate: {
      finding: 'One or more GST returns filed late in the past 12 months.',
      recommendation: 'File all overdue returns immediately; pay late fees (Rs.50/day for GSTR-3B; Rs.200/day for GSTR-9). Set up auto-reminders. Engage CA for GSTR-9C reconciliation.',
      timeline: '30_days',
      penaltyExposure: 'Rs.50/day (Rs.20 nil return); Sec 73/74 demand + penalty up to 100% of tax for ITC mismatch',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (_p: ApplicabilityProfile) => true,
  },
  {
    id: 'AD_P2_021',
    phase: 2,
    text: 'Is TCS u/s 206C(1F) collected at 1% on all vehicle sales where the invoice value exceeds Rs.10 lakh per transaction, and are Form 27EQ quarterly returns filed?',
    helpText: 'TCS under s.206C(1F) applies on motor vehicle sales >Rs.10 lakh per transaction at 1%. Effective 22 Apr 2025, TCS also applies on luxury goods (watches, art, handbags, sports gear, home theatre, horses) >Rs.10 lakh per item. Deposit by 7th; Form 27EQ quarterly; Form 27D to buyer within 15 days of return.',
    type: 'yes_no',
    weight: 8,
    complianceArea: 'tds_tcs',
    source: 'Research §4.8, IT Act §206C(1F), CBDT Notification 36/2025',
    gapTemplate: {
      finding: 'TCS not collected or Form 27EQ not filed for vehicle sales >Rs.10 lakh.',
      recommendation: 'Configure DMS to auto-flag invoices >Rs.10 lakh; collect TCS at billing; deposit by 7th; file Form 27EQ quarterly; issue Form 27D to buyer within 15 days.',
      timeline: '30_days',
      penaltyExposure: 'Equal to TCS amount + 1% interest per month; disallowance of deduction on income tax computation',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (_p: ApplicabilityProfile) => true,
  },
  {
    id: 'AD_P2_022',
    phase: 2,
    text: 'Are all TDS obligations (192/194C/194H/194I/194J/194Q) deposited by the 7th and Form 24Q/26Q returns filed quarterly?',
    helpText: 'Key TDS obligations for dealerships: 194C on contract payments (washer/valet contractors); 194H on commission/brokerage; 194I on rent if >Rs.2.4 lakh/year; 194Q on purchases >Rs.50 lakh/year; 192 on salaries.',
    type: 'yes_no',
    weight: 7,
    complianceArea: 'tds_tcs',
    source: 'Research §4.8, IT Act Chapters XVII-B/XVII-BB',
    gapTemplate: {
      finding: 'TDS not deposited by 7th or quarterly returns (24Q/26Q) not filed.',
      recommendation: 'Set up auto-debit for TDS by 7th of month; file 24Q/26Q by 15th of month following quarter-end; clear arrears + interest immediately.',
      timeline: '30_days',
      penaltyExposure: '1% per month interest (non-deduction); 1.5% per month (non-deposit); penalty equal to TDS under §271C',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (_p: ApplicabilityProfile) => true,
  },
  {
    id: 'AD_P2_023',
    phase: 2,
    text: 'Are e-way bills generated for all inter-state stock transfers and customer deliveries where value exceeds Rs.50,000?',
    helpText: 'E-way bills are mandatory for inter-state movement of goods >Rs.50,000. For intra-state, threshold varies by state (most: Rs.50,000). Vehicles moving from stockyard to showroom or for PDI without e-way bills attract penalty.',
    type: 'yes_no',
    weight: 7,
    complianceArea: 'gst',
    source: 'Research §4.8, CGST Rules 2017 Rule 138',
    gapTemplate: {
      finding: 'E-way bills not consistently generated for vehicle transfers.',
      recommendation: 'Integrate DMS with GST e-way bill portal; generate e-way bills for all inter-state and applicable intra-state movements; monitor validity.',
      timeline: '30_days',
      penaltyExposure: 'Rs.10,000 or tax-due (whichever higher) per movement; vehicle seizure possible',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (_p: ApplicabilityProfile) => true,
  },
  {
    id: 'AD_P2_024',
    phase: 2,
    text: 'If applicable, has the income-tax return and tax audit report (Form 3CD u/s 44AB) been filed on time? Is SFT (Form 61A) filed for cash receipts >=Rs.2 lakh from vehicle sale?',
    helpText: 'Tax audit is mandatory if turnover >Rs.1 crore (or >Rs.10 crore if >=95% transactions are digital). SFT requires reporting of high-value cash transactions; Form 60/61 mandatory for cash receipts >Rs.2 lakh without PAN.',
    type: 'yes_no',
    weight: 6,
    complianceArea: 'tds_tcs',
    source: 'Research §4.8, IT Act §44AB, Rule 114E',
    gapTemplate: {
      finding: 'Tax audit / SFT filing status not confirmed.',
      recommendation: 'Confirm tax audit applicability with CA; file Form 3CD by 30 Sep; file SFT (Form 61A) by 31 May; maintain Form 60/61 register for high-value cash.',
      timeline: '90_days',
      penaltyExposure: 'Rs.1.5 lakh penalty for non-audit u/s 271B; Rs.500/day for late SFT u/s 271FA',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (p: ApplicabilityProfile) => turnoverGte(p, 1),
  },
  {
    id: 'AD_P2_025',
    phase: 2,
    text: 'Is reverse-charge GST paid on legal/professional fees, GTA (Goods Transport Agency) services, and other RCM supplies?',
    helpText: 'Dealerships commonly miss RCM on: legal fees to advocates; transport charges to GTA; import of services; sponsorship fees (if paid). RCM amount must be paid via cash ledger (ITC cannot offset RCM liability).',
    type: 'yes_no',
    weight: 6,
    complianceArea: 'gst',
    source: 'Research §4.8, CGST Act §9(3)',
    gapTemplate: {
      finding: 'Reverse-charge GST not consistently paid on applicable services.',
      recommendation: 'List all vendors liable for RCM; configure ERP/accounts to auto-flag RCM entries; include in GSTR-3B (Column 3.1d); pay by 20th of following month.',
      timeline: '30_days',
      penaltyExposure: 'GST demand + interest 18% + penalty up to 100% of tax on RCM shortfall',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (_p: ApplicabilityProfile) => true,
  },
  {
    id: 'AD_P2_026',
    phase: 2,
    text: 'Is the ITC on demo cars supported by "use in furtherance of supply" documentation, and is the transitional cess-credit position documented?',
    helpText: 'ITC on demo vehicles is a grey area — some AARs have disallowed it. FADA litigation on transitional GST 2.0 cess credit is ongoing. Documenting business use (test-drive logs) mitigates disallowance risk.',
    type: 'single_choice',
    options: [
      { value: 'documented',    label: 'Yes — test-drive logs and CA opinion on ITC documented' },
      { value: 'partial',       label: 'Partially — some documentation but not complete' },
      { value: 'not_claimed',   label: 'ITC on demo cars not claimed (conservative approach)' },
      { value: 'no',            label: 'No documentation — ITC claimed without records' },
    ],
    weight: 5,
    complianceArea: 'gst',
    source: 'Research §9.6 (flag), CGST Act §17(5)',
    gapTemplate: {
      finding: 'ITC on demo cars claimed without adequate documentation — audit risk.',
      recommendation: 'Maintain job-card style test-drive logs; obtain CA opinion on ITC eligibility in your specific context; document transitional cess credit position (FADA litigation pending).',
      timeline: '90_days',
      penaltyExposure: 'Disallowance of ITC + demand + 18% interest + penalty up to 100%; SCN likely in GST audit',
    },
    compliantAnswers: ['documented', 'not_claimed'],
    partiallyCompliantAnswers: ['partial'],
    appliesWhen: (_p: ApplicabilityProfile) => true,
  },

  // --------------------------------------------------------------------------
  // Maternity
  // --------------------------------------------------------------------------
  {
    id: 'AD_P2_027',
    phase: 2,
    text: 'If you have 30 or more women employees (or 50 under Maternity Benefit Act), is a creche facility provided or arranged within a prescribed distance?',
    helpText: 'Factories Act §48: creche required if >=30 women workers. Maternity Benefit (Amendment) Act 2017 §11A: creche required if >=50 employees (not just women). Alternatively, employer may tie up with a nearby creche and meet the cost.',
    type: 'yes_no',
    weight: 6,
    complianceArea: 'maternity',
    source: 'Research §4.2, Factories Act §48, Maternity Benefit Act §11A',
    gapTemplate: {
      finding: 'Creche not provided despite threshold of women/total employees being crossed.',
      recommendation: 'Establish creche at or near workplace, or tie up with a registered creche; allow women to visit 4 times a day including rest intervals; notify employees of creche location.',
      timeline: '90_days',
      penaltyExposure: 'Rs.10,000 to Rs.50,000 per default; repeat = Rs.1 lakh; imprisonment up to 3 months',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (p: ApplicabilityProfile) =>
      p.womenEmployeeCount === '30_49' || p.womenEmployeeCount === 'gte_50',
  },

  // --------------------------------------------------------------------------
  // Legacy Labour Acts toggle questions
  // --------------------------------------------------------------------------
  {
    id: 'AD_P2_028',
    phase: 2,
    text: 'Under the legacy regime (Factories Act 1948 Form IV Annual Registration) — is your factory licence Form 4 current and displayed at the factory entrance?',
    helpText: 'If operating under the legacy Factories Act (state-specific transition to OSH Code still pending), Form 4 factory licence must be renewed annually or as per state rules, displayed at main entrance.',
    type: 'yes_no',
    weight: 8,
    complianceArea: 'factories_osh',
    source: 'Research §4.3, Factories Act 1948 §6',
    gapTemplate: {
      finding: 'Factory licence (Form 4) not confirmed as current under legacy regime.',
      recommendation: 'Renew Form 4 through state Factory Inspector portal. Display at factory entrance. Ensure licence covers current worker count and power load.',
      timeline: '30_days',
      penaltyExposure: 'Up to Rs.5 lakh + imprisonment up to 2 yrs for unlicensed factory operation',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (p: ApplicabilityProfile) =>
      p.labourRegime === 'legacy' && p.hasWorkshop && employeeGte(p, 10),
  },
  {
    id: 'AD_P2_029',
    phase: 2,
    text: 'Is the Contract Labour Registration Certificate (RC) from the Labour Commissioner current and does it name all current contractors and their headcount?',
    helpText: 'Under Contract Labour (R&A) Act, the principal employer (dealership) must hold an RC if it employs >=20 contract workers. The RC must be updated when contractors or headcount changes.',
    type: 'yes_no',
    weight: 7,
    complianceArea: 'contract_labour',
    source: 'Research §4.4, Contract Labour (R&A) Act 1970 §7',
    gapTemplate: {
      finding: 'RC for contract labour not current or not covering all contractors.',
      recommendation: 'Apply for RC from Labour Commissioner (Form I); update when contractors change; display RC at premises.',
      timeline: '30_days',
      penaltyExposure: 'Rs.500 to Rs.1,000 per default; prosecution; denial of contract work',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (p: ApplicabilityProfile) =>
      p.hasContractLabour && p.contractWorkerCount >= 20,
  },
  {
    id: 'AD_P2_030',
    phase: 2,
    text: 'Are contractor wages, EPF/ESI deposits, and PPE provisions verified monthly by the principal employer (dealership), and is a wage parity check done for workers doing similar work?',
    helpText: 'Under the Code on Wages / Contract Labour Act, the principal employer is liable for contractor wage defaults. Wage parity (same/similar work) is now a compliance obligation. PPE, drinking water, and latrines must be available to all contract workers.',
    type: 'yes_no',
    weight: 7,
    complianceArea: 'contract_labour',
    source: 'Research §4.4, Code on Wages 2019 §6',
    gapTemplate: {
      finding: 'Contractor wage parity / EPF-ESI verification not done monthly.',
      recommendation: 'Collect proof of EPF/ESI deposit from contractor monthly; conduct quarterly wage parity audit; ensure contract workers have access to PPE, water, sanitation.',
      timeline: '30_days',
      penaltyExposure: 'Principal employer\'s liability for contractor default; prosecution under EPF Act + Contract Labour Act',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (p: ApplicabilityProfile) => p.hasContractLabour,
  },
]
