// ============================================================================
// Phase 3 — Workshop EHS (~25 questions)
// Source: Research §4.3 Factories/OSH, §4.4 Contract Labour, §4.7 PESO/Fire,
//         §4.6 partial (SPCB/HW)
// All questions gated by p.hasWorkshop === true (except fire NOC which also
// applies to large showrooms).
// ============================================================================

import type { AutoDealerQuestion, ApplicabilityProfile } from '@/types/auto-dealer'
import { employeeGte } from './rules-engine'

const workshopOnly = (p: ApplicabilityProfile): boolean => p.hasWorkshop
const workshopAndWorkers = (p: ApplicabilityProfile): boolean =>
  p.hasWorkshop && employeeGte(p, 10)

export const PHASE3_WORKSHOP_EHS_QUESTIONS: AutoDealerQuestion[] = [
  // --------------------------------------------------------------------------
  // Factories Act / OSH Code
  // --------------------------------------------------------------------------
  {
    id: 'AD_P3_001',
    phase: 3,
    text: 'Has a factory licence (Form 4 under Factories Act / OSH Code) been obtained and is it current for the actual worker count and installed power?',
    helpText: 'A workshop employing 10+ workers using power (or 20+ without power) is a "factory" under the Factories Act. Licence must be renewed when worker count or power increases. The predominant-activity test: a primarily showroom business with only minor servicing may remain a "shop" — seek legal opinion if borderline.',
    type: 'yes_no',
    weight: 10,
    complianceArea: 'factories_osh',
    source: 'Research §4.3, Factories Act 1948 §2(m), §6',
    gapTemplate: {
      finding: 'Factory licence not confirmed — unlicensed factory operation is a criminal offence.',
      recommendation: 'Apply for Form 4 licence through state factory inspector portal immediately. Disclose correct worker count and power. Do not increase capacity before obtaining amended licence.',
      timeline: '30_days',
      penaltyExposure: 'Up to Rs.5 lakh fine; imprisonment up to 2 yrs for occupier/manager; sealing of factory',
    },
    compliantAnswers: ['yes'],
    appliesWhen: workshopAndWorkers,
  },
  {
    id: 'AD_P3_002',
    phase: 3,
    text: 'Is the Form 11 register of adult workers (and Form 14 for child/adolescent workers) maintained and available for inspection?',
    helpText: 'Factories Act requires a register of all workers with their hours, wages, and overtime. OSH Code similarly requires a digital register. Absence of registers is the first finding in any labour inspection.',
    type: 'yes_no',
    weight: 6,
    complianceArea: 'factories_osh',
    source: 'Research §4.3, Factories Act 1948 §62, §73',
    gapTemplate: {
      finding: 'Worker registers (Form 11) not maintained.',
      recommendation: 'Set up Form 11 register (paper or digital) for all workers; update attendance, OT, and wages monthly.',
      timeline: '30_days',
      penaltyExposure: 'Rs.1 lakh fine for each default in register maintenance',
    },
    compliantAnswers: ['yes'],
    appliesWhen: workshopAndWorkers,
  },
  {
    id: 'AD_P3_003',
    phase: 3,
    text: 'Have all vehicle lifts, two-post/four-post hoists, and cranes been certified by a Competent Person (Form 8/9) within the last 12 months?',
    helpText: 'Factories Act §28 requires all lifting machines to be examined by a Competent Person at least once every 12 months. Form 8 is for lifting machines; Form 9 for pressure vessels. Uncertified lifts are a critical safety and compliance finding.',
    type: 'yes_no',
    weight: 9,
    complianceArea: 'factories_osh',
    source: 'Research §4.3, Factories Act 1948 §28-29',
    gapTemplate: {
      finding: 'Vehicle lifts / hoists not certified by Competent Person in last 12 months.',
      recommendation: 'Engage a PESO / Factory-approved Competent Person for annual inspection; obtain Form 8 certificate; do not operate uncertified lifts.',
      timeline: '30_days',
      penaltyExposure: 'Rs.5 lakh fine if worker injury occurs on uncertified equipment; criminal prosecution possible',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (p: ApplicabilityProfile) => p.hasWorkshop && p.hasLiftsOrHoists,
  },
  {
    id: 'AD_P3_004',
    phase: 3,
    text: 'Are air compressors and pressure vessels hydraulic-tested annually and records maintained?',
    helpText: 'Air compressors are pressure vessels under Factories Act §31. Annual hydraulic test by Competent Person is mandatory. Failures can cause serious injury and criminal liability for occupier.',
    type: 'yes_no',
    weight: 8,
    complianceArea: 'factories_osh',
    source: 'Research §4.3, Factories Act 1948 §31',
    gapTemplate: {
      finding: 'Pressure vessels (air compressors) not hydraulic-tested annually.',
      recommendation: 'Schedule annual hydraulic test with PESO-approved Competent Person; maintain Form 9 certificates; display maximum allowable pressure placard.',
      timeline: '30_days',
      penaltyExposure: 'Rs.5 lakh fine + criminal prosecution if explosion occurs without valid certificate',
    },
    compliantAnswers: ['yes'],
    appliesWhen: workshopOnly,
  },
  {
    id: 'AD_P3_005',
    phase: 3,
    text: 'Are paint-booth pollution-control equipment (scrubbers, mist eliminators, activated-carbon filters) inspected, operational, and logged?',
    helpText: 'Paint booths generate VOC emissions and paint sludge (a hazardous waste). SPCB Air Consent requires pollution-control equipment to be operational at all times. Inspection logs must be maintained.',
    type: 'yes_no',
    weight: 8,
    complianceArea: 'spcb',
    source: 'Research §4.3, Air (Prevention & Control of Pollution) Act 1981',
    gapTemplate: {
      finding: 'Paint-booth pollution control equipment not verified as operational and logged.',
      recommendation: 'Inspect scrubber / mist eliminator monthly; log maintenance dates; replace filter media as per manufacturer schedule; include in CTO compliance report.',
      timeline: '30_days',
      penaltyExposure: 'SPCB closure order u/s 31A Air Act; EC Rs.1 lakh to Rs.1 crore; imprisonment up to 5 yrs',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (p: ApplicabilityProfile) => p.hasWorkshop && p.hasPaintBooth,
  },
  {
    id: 'AD_P3_006',
    phase: 3,
    text: 'Is PPE (gloves, goggles, aprons, hearing protection, respiratory masks) issued and usage enforced for all body-shop, paint, and battery-handling workers?',
    helpText: 'PPE issuance is mandatory under Factories Act §14 and OSH Code §22. For hazardous-process workers (spray-painters, welders, battery handlers), enforcement — not just issuance — is assessed by inspectors.',
    type: 'yes_no',
    weight: 7,
    complianceArea: 'factories_osh',
    source: 'Research §4.3, Factories Act 1948 §14, OSH Code 2020 §22',
    gapTemplate: {
      finding: 'PPE issuance register not maintained or usage not enforced.',
      recommendation: 'Maintain PPE issuance register (worker-wise, date-wise, item-wise); conduct monthly PPE inspection; issue non-usage memo; replace damaged PPE immediately.',
      timeline: '30_days',
      penaltyExposure: 'Rs.2 lakh per default under OSH Code; injury attributable to PPE failure creates employer liability',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (p: ApplicabilityProfile) => p.hasWorkshop && p.hasHazardousProcessWorkers,
  },
  {
    id: 'AD_P3_007',
    phase: 3,
    text: 'Are Material Safety Data Sheets (MSDS) / Safety Data Sheets (SDS) displayed at chemical storage areas, and is secondary containment provided for oils, solvents, and paints?',
    helpText: 'MSDS display is required under Factories Act Schedule-IV. Secondary containment (bunds) prevents soil and drain contamination — an SPCB inspection priority. Paints, thinners, degreasers, brake fluid, and battery acid all require MSDS.',
    type: 'yes_no',
    weight: 7,
    complianceArea: 'hazardous_waste',
    source: 'Research §4.3, Factories Act 1948 Sch. IV',
    gapTemplate: {
      finding: 'MSDS not displayed or secondary containment absent at chemical storage.',
      recommendation: 'Obtain SDS from chemical suppliers; laminate and display at each chemical storage point; construct concrete bunds around oil/solvent storage; install drip trays under dispensing points.',
      timeline: '30_days',
      penaltyExposure: 'SPCB EC Rs.1 lakh to Rs.1 crore; closure order for spillage',
    },
    compliantAnswers: ['yes'],
    appliesWhen: workshopOnly,
  },
  {
    id: 'AD_P3_008',
    phase: 3,
    text: 'Is a hot-work permit system documented and a Lock-Out Tag-Out (LOTO) procedure implemented for electrical/mechanical work?',
    helpText: 'Hot-work (welding, cutting, grinding) near flammable materials requires a formal permit system under Factories Act. LOTO prevents accidental energisation during repair. Both are assessed by Factory Inspectors during scheduled and surprise visits.',
    type: 'yes_no',
    weight: 7,
    complianceArea: 'factories_osh',
    source: 'Research §4.3, Factories Act 1948 §36A',
    gapTemplate: {
      finding: 'Hot-work permit or LOTO procedure not documented.',
      recommendation: 'Implement written hot-work permit form (approval, fire-watch, area check, post-work inspection); display LOTO procedure at electrical panels; train all technicians.',
      timeline: '30_days',
      penaltyExposure: 'Rs.5 lakh fine + criminal prosecution if fire/injury occurs without permit system',
    },
    compliantAnswers: ['yes'],
    appliesWhen: workshopOnly,
  },
  {
    id: 'AD_P3_009',
    phase: 3,
    text: 'Is there at least one first-aid trained person for every 150 workers, and is the first-aid box equipped as per Factory Rules?',
    helpText: 'Factories Act §45: at least one first-aid box per 150 workers; box contents specified in state factory rules; must be in charge of a trained person (certificate required). Expired medicines in the first-aid box is the most common inspection finding.',
    type: 'yes_no',
    weight: 6,
    complianceArea: 'factories_osh',
    source: 'Research §4.3, Factories Act 1948 §45',
    gapTemplate: {
      finding: 'First-aid trained staff or equipped first-aid box not present.',
      recommendation: 'Train at least 1 person per 150 workers in first aid; equip first-aid box per state rules; check and restock monthly; display first-aider name and location.',
      timeline: '30_days',
      penaltyExposure: 'Rs.1 lakh fine per default; employer liability in any accident',
    },
    compliantAnswers: ['yes'],
    appliesWhen: workshopAndWorkers,
  },
  {
    id: 'AD_P3_010',
    phase: 3,
    text: 'Are annual return Form 22 and half-yearly return Form 21 filed with the Inspector of Factories within due dates (31 Jan and 15 Jul / 15 Jan respectively)?',
    helpText: 'Form 22 (annual) must be filed by 31 January for the previous year. Form 21 (half-yearly) by 15 July (first half) and 15 January (second half). Notifiable accidents must be reported within 4 hours on Form 18.',
    type: 'yes_no',
    weight: 6,
    complianceArea: 'factories_osh',
    source: 'Research §4.3, Factories Act 1948 §88-92',
    gapTemplate: {
      finding: 'Factories returns not filed within due dates.',
      recommendation: 'File Form 22 by 31 Jan; Form 21 by 15 Jul and 15 Jan; set calendar reminders. Report notifiable accidents on Form 18 within 4 hours.',
      timeline: '30_days',
      penaltyExposure: 'Rs.1 lakh fine for late filing; Rs.2 lakh for accident non-reporting',
    },
    compliantAnswers: ['yes'],
    appliesWhen: workshopAndWorkers,
  },

  // --------------------------------------------------------------------------
  // SPCB Consents
  // --------------------------------------------------------------------------
  {
    id: 'AD_P3_011',
    phase: 3,
    text: 'Has a Consent to Establish (CTE) been obtained from the SPCB before constructing or expanding the workshop?',
    helpText: 'Any new workshop or expansion of existing workshop requires CTE under Water Prevention & Control of Pollution Act 1974 and Air Prevention & Control of Pollution Act 1981 before construction begins. Operating without CTE is a serious violation.',
    type: 'yes_no',
    weight: 9,
    complianceArea: 'spcb',
    source: 'Research §4.6, Water Act 1974 §25, Air Act 1981 §21',
    gapTemplate: {
      finding: 'CTE not confirmed prior to workshop construction — SPCB non-compliance.',
      recommendation: 'Obtain CTE retrospectively (many SPCBs have one-time compounding scheme); ensure all future expansions have prior CTE. Apply through state SPCB portal.',
      timeline: '90_days',
      penaltyExposure: 'SPCB EC Rs.1 lakh to Rs.1 crore; closure order under EPA §5; criminal prosecution',
    },
    compliantAnswers: ['yes'],
    appliesWhen: workshopOnly,
  },
  {
    id: 'AD_P3_012',
    phase: 3,
    text: 'Is the Consent to Operate (CTO) from the SPCB valid and covering both Air and Water Acts for the full installed workshop capacity?',
    helpText: 'CTO must be renewed typically every 1-5 years (varies by state and SPCB category). A "Red" or "Orange" category workshop must have CTO before operations begin. Paint booths trigger Air Act consent.',
    type: 'yes_no',
    weight: 10,
    complianceArea: 'spcb',
    source: 'Research §4.6, Water Act 1974 §26, Air Act 1981 §21',
    gapTemplate: {
      finding: 'CTO not confirmed or expired — operating without CTO is the highest EHS risk.',
      recommendation: 'Apply for CTO renewal >=60 days before expiry; ensure both Water and Air Act consents are live; display CTO at workshop entrance.',
      timeline: '30_days',
      penaltyExposure: 'SPCB closure order under EPA §5; EC Rs.1 lakh to Rs.1 crore; 5 yr imprisonment for wilful violation',
    },
    compliantAnswers: ['yes'],
    appliesWhen: workshopOnly,
  },
  {
    id: 'AD_P3_013',
    phase: 3,
    text: 'Is a Hazardous Waste (HW) Authorisation under HW Rules 2016 valid, and is Form 3 inventory maintained and Form 10 manifest completed for every HW consignment?',
    helpText: 'Workshop HW includes: used oil, paint sludge, coolant waste, solvent waste, chemical containers, lead-acid battery fragments, and ELV shredder residue. Form 3 = HW inventory register. Form 10 = manifest for each transport. Form 4 = annual return by 30 June.',
    type: 'yes_no',
    weight: 9,
    complianceArea: 'hazardous_waste',
    source: 'Research §4.6, HOWM Rules 2016 Rule 7',
    gapTemplate: {
      finding: 'HW Authorisation not confirmed or Form 3/10 records missing.',
      recommendation: 'Apply for HW Authorisation from SPCB; maintain Form 3 inventory; use Form 10 manifest for every transport; sell used oil only to MoEFCC-listed re-refiners.',
      timeline: '30_days',
      penaltyExposure: 'EC Rs.1 lakh to Rs.1 crore; closure; imprisonment up to 5 yrs (EPA §15 for wilful violation)',
    },
    compliantAnswers: ['yes'],
    appliesWhen: workshopOnly,
  },
  {
    id: 'AD_P3_014',
    phase: 3,
    text: 'Is used oil channelised ONLY to MoEFCC/CPCB-registered re-refiners, and is Form 4 annual HW return filed by 30 June each year?',
    helpText: 'Used engine oil is a hazardous waste. Selling to unregistered buyers (roadside mechanics, informal collectors) violates HW Rules. CPCB maintains a list of registered re-refiners at cpcb.nic.in.',
    type: 'yes_no',
    weight: 8,
    complianceArea: 'hazardous_waste',
    source: 'Research §4.6, HOWM Rules 2016 Rule 9',
    gapTemplate: {
      finding: 'Used oil sold to unregistered buyers or Form 4 return not filed.',
      recommendation: 'List CPCB-registered re-refiners in your state; use Form 10 manifest for each transfer; file Form 4 annual HW return by 30 June.',
      timeline: '30_days',
      penaltyExposure: 'EC Rs.1 lakh to Rs.1 crore; EC levied per CPCB schedule; criminal action under EPA',
    },
    compliantAnswers: ['yes'],
    appliesWhen: workshopOnly,
  },
  {
    id: 'AD_P3_015',
    phase: 3,
    text: 'Are the hazardous waste storage area on premises bunded, ventilated, labelled, and locked — with secondary containment for liquids?',
    helpText: 'CPCB HW storage guidelines require: concrete bunding >=110% of largest container volume; ventilation; GHS labels on all containers; locked storage to prevent unauthorised access; separation of incompatible wastes.',
    type: 'yes_no',
    weight: 7,
    complianceArea: 'hazardous_waste',
    source: 'Research §4.6, HOWM Rules 2016 Sch. II',
    gapTemplate: {
      finding: 'HW storage area does not meet CPCB guidelines (bunding, labelling, ventilation).',
      recommendation: 'Construct concrete bunding; install ventilation; apply GHS hazard labels; lock storage; separate used oil from paint sludge. Photograph compliance for SPCB records.',
      timeline: '90_days',
      penaltyExposure: 'EC Rs.1 lakh to Rs.1 crore; SPCB notice; imminent-danger closure under EPA §5',
    },
    compliantAnswers: ['yes'],
    appliesWhen: workshopOnly,
  },
  {
    id: 'AD_P3_016',
    phase: 3,
    text: 'Is the oil-water separator operational and its effluent quality monitored quarterly through a NABL-accredited laboratory?',
    helpText: 'Workshops discharge wash-water and floor runoff via drains. SPCB consents require an oil-water separator with effluent standards (oil <=10 mg/L for surface discharge). Quarterly NABL lab reports are a standard SPCB inspection requirement.',
    type: 'yes_no',
    weight: 7,
    complianceArea: 'spcb',
    source: 'Research §4.6, Water Act 1974',
    gapTemplate: {
      finding: 'Oil-water separator absent or not monitored — effluent standard compliance unverified.',
      recommendation: 'Install/maintain oil-water separator; engage NABL lab for quarterly effluent test; maintain test certificates; include in CTO compliance report.',
      timeline: '90_days',
      penaltyExposure: 'SPCB Notice; EC Rs.1 lakh to Rs.1 crore; closure for persistent effluent violation',
    },
    compliantAnswers: ['yes'],
    appliesWhen: workshopOnly,
  },

  // --------------------------------------------------------------------------
  // PESO & Fire
  // --------------------------------------------------------------------------
  {
    id: 'AD_P3_017',
    phase: 3,
    text: 'For diesel/petrol storage >2,500 litres — is the PESO licence (Form XIV or Form XV) current and the licence number displayed at the storage area?',
    helpText: 'Storage >2,500 L up to 25,000 L requires Form XIV from PESO Regional Office. >25,000 L requires Form XV. Licence conditions specify containment walls, earthing, "No Smoking" signs, and minimum distances from ignition sources.',
    type: 'yes_no',
    weight: 9,
    complianceArea: 'peso_fire',
    source: 'Research §4.7, Petroleum Rules 2002 Rule 139',
    gapTemplate: {
      finding: 'PESO licence not confirmed for diesel/petrol storage >2,500 L.',
      recommendation: 'Apply for PESO Form XIV/XV licence; ensure storage area complies with Petroleum Rules 2002 (separation, containment, earthing); display licence number.',
      timeline: '30_days',
      penaltyExposure: 'Up to Rs.50,000 fine + closure + cancellation under Petroleum Act §23',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (p: ApplicabilityProfile) => p.dieselStorageLitres > 2500,
  },
  {
    id: 'AD_P3_018',
    phase: 3,
    text: 'Is the Fire NOC from the State Fire Services Department current, and are fire extinguishers, hose reels, and fire alarm system maintained and recently refilled/tested?',
    helpText: 'Fire NOC is required from State Fire Services for commercial premises (area thresholds vary by state). Fire extinguishers must be refilled annually; ABC/CO2 types in workshop; hydrostatic test every 3 years. Fire panel self-test monthly.',
    type: 'yes_no',
    weight: 9,
    complianceArea: 'peso_fire',
    source: 'Research §4.7, State Fire Prevention Acts',
    gapTemplate: {
      finding: 'Fire NOC not current or fire-fighting equipment not maintained.',
      recommendation: 'Renew Fire NOC before expiry; schedule annual FE refilling; test fire alarm monthly; conduct mock fire drill every 6 months; maintain drill register.',
      timeline: '30_days',
      penaltyExposure: 'Sealing + Rs.10,000 to Rs.1 lakh (state-variable) for operating without Fire NOC',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (p: ApplicabilityProfile) =>
      p.hasWorkshop || (p.showroomAreaSqft ?? 0) > 500,
  },
  {
    id: 'AD_P3_019',
    phase: 3,
    text: 'Have oxygen and acetylene cylinders been stored separately, chained vertically in a shaded area, with flash-back arrestors fitted on all outlets?',
    helpText: 'Oxy-acetylene storage compliance per Gas Cylinder Rules 2016: cylinders must be stored separately (min 3m between O2 and fuel gas), chained upright, shaded from direct sun, "No Smoking" sign, flash-back arrestors fitted. Many workshop fires originate from oxy-acetylene non-compliance.',
    type: 'yes_no',
    weight: 8,
    complianceArea: 'peso_fire',
    source: 'Research §4.7, Gas Cylinder Rules 2016',
    gapTemplate: {
      finding: 'Oxy-acetylene cylinder storage non-compliant with Gas Cylinder Rules 2016.',
      recommendation: 'Separate O2 and fuel cylinders by >=3m or fire-resistant wall; chain vertical; fit flash-back arrestors; display "No Smoking" sign; train welders on safe handling.',
      timeline: '30_days',
      penaltyExposure: 'Rs.5,000 to Rs.50,000 under Gas Cylinders Rules; explosion liability is criminal',
    },
    compliantAnswers: ['yes'],
    appliesWhen: workshopOnly,
  },
  {
    id: 'AD_P3_020',
    phase: 3,
    text: 'In the paint-booth and paint-mixing area — are all electrical fittings explosion-proof (PESO/ATEX-rated) and is the area ventilated to maintain solvent vapour below LEL?',
    helpText: 'Paint-mixing rooms and spray booths are classified as Zone 1 or Zone 2 hazardous areas under PESO/ATEX. Standard electrical fittings are not permissible. Ventilation must dilute VOCs to <25% of Lower Explosive Limit (LEL). A single spark in a non-compliant booth can cause catastrophic fire.',
    type: 'yes_no',
    weight: 9,
    complianceArea: 'peso_fire',
    source: 'Research §4.7, PESO Petroleum Rules 2002 Sch. II',
    gapTemplate: {
      finding: 'Paint-booth electrical fittings may not be ATEX-rated — explosion risk.',
      recommendation: 'Replace all standard fittings in paint-booth with ATEX/PESO-approved Ex-rated equipment. Fit LEL monitor with audible alarm. Inspect ventilation rate per manufacturer spec.',
      timeline: '30_days',
      penaltyExposure: 'PESO licence cancellation; criminal liability under Petroleum Act for fire/explosion; potential manslaughter charges',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (p: ApplicabilityProfile) => p.hasWorkshop && p.hasPaintBooth,
  },
  {
    id: 'AD_P3_021',
    phase: 3,
    text: 'Has a mock fire drill been conducted in the last 6 months and recorded in the Fire Register?',
    helpText: 'State fire departments and the Ministry of Labour require regular fire drills. Recommended frequency: twice a year. Drill records must show date, time, evacuation time, and coordinator\'s signature.',
    type: 'yes_no',
    weight: 5,
    complianceArea: 'peso_fire',
    source: 'Research §4.7, National Building Code 2016',
    gapTemplate: {
      finding: 'Mock fire drill not conducted in the last 6 months.',
      recommendation: 'Schedule fire drill within 30 days; involve all staff including contract workers; record time to evacuate; identify and fix bottlenecks; send drill report to State Fire Service if required.',
      timeline: '30_days',
      penaltyExposure: 'Fire NOC revocation risk; employer liability in any fire-related injury',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (p: ApplicabilityProfile) =>
      p.hasWorkshop || (p.showroomAreaSqft ?? 0) > 1000,
  },
  {
    id: 'AD_P3_022',
    phase: 3,
    text: 'For EV charging stations — has CEIG (Chief Electrical Inspector to Government) NOC and Type-2/CCS-2 charger certification been obtained, and is a fire-detection system installed?',
    helpText: 'EV fast chargers (>3.5 kW) require CEIG NOC before commissioning. BIS certification for chargers: IS 17017 (AC) / IS 17017-2 (DC). Fire risks from Li-ion battery thermal runaway require dedicated smoke detectors and CO2 extinguishers near charging bays.',
    type: 'yes_no',
    weight: 7,
    complianceArea: 'peso_fire',
    source: 'Research §4.7, CEA Regulations 2023, BIS IS 17017',
    gapTemplate: {
      finding: 'EV charger installed without CEIG NOC or fire detection.',
      recommendation: 'Obtain CEIG NOC; verify charger carries BIS IS 17017 mark; install smoke detector and CO2 extinguisher at each charging bay; display emergency cut-off switch.',
      timeline: '90_days',
      penaltyExposure: 'CEA penalty; PESO action; potential shutdown if fire-safety deficiency found',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (p: ApplicabilityProfile) => p.hasEVCharger,
  },
  {
    id: 'AD_P3_023',
    phase: 3,
    text: 'Are CNG/LPG cylinder storage areas compliant with SMPV (Unfired Pressure Vessels) Rules 2016 — earthed, ventilated, with approved regulator, and no smoking signage?',
    helpText: 'CNG dispensers and LPG installations at dealerships are governed by PESO and SMPV Rules 2016. Annual inspection by a Competent Person is mandatory. Earthing prevents static-electricity ignition.',
    type: 'yes_no',
    weight: 7,
    complianceArea: 'peso_fire',
    source: 'Research §4.7, SMPV Rules 2016',
    gapTemplate: {
      finding: 'CNG/LPG installation compliance with SMPV Rules 2016 unverified.',
      recommendation: 'Engage PESO-approved Competent Person for annual inspection; check earthing; display PESO licence; mark safety zone; no open flames within 3m.',
      timeline: '30_days',
      penaltyExposure: 'PESO licence cancellation; criminal liability under Petroleum Act',
    },
    compliantAnswers: ['yes'],
    appliesWhen: (p: ApplicabilityProfile) => p.hasCNGDispenser,
  },
  {
    id: 'AD_P3_024',
    phase: 3,
    text: 'Are water cess charges paid and quarterly effluent-quality monitoring done through a NABL-accredited lab as required by SPCB conditions?',
    helpText: 'The Water (Prevention and Control of Pollution) Cess Act 1977 levies cess on water consumption for industrial/commercial use. SPCB CTO conditions typically require quarterly effluent testing by NABL labs.',
    type: 'yes_no',
    weight: 6,
    complianceArea: 'spcb',
    source: 'Research §4.6, Water Cess Act 1977',
    gapTemplate: {
      finding: 'Water cess unpaid or NABL effluent monitoring not done quarterly.',
      recommendation: 'Register for water cess with SPCB; pay cess by due date; engage NABL lab for quarterly monitoring; include reports in CTO renewal file.',
      timeline: '90_days',
      penaltyExposure: 'Water cess arrears + interest; CTO renewal rejection if monitoring not done',
    },
    compliantAnswers: ['yes'],
    appliesWhen: workshopOnly,
  },
  {
    id: 'AD_P3_025',
    phase: 3,
    text: 'Is the workshop clean, with designated PPE station, spill-kit available, and emergency contact numbers displayed?',
    helpText: 'Good housekeeping reduces injury risk and impresses inspectors. OSH Code requires: clean gangways, spill kits near chemical storage, first-aid numbers, emergency assembly points, and safety officer appointment if >250 workers.',
    type: 'yes_no',
    weight: 4,
    complianceArea: 'factories_osh',
    source: 'Research §4.3, OSH Code 2020 §24',
    gapTemplate: {
      finding: 'Workshop housekeeping, PPE station, or emergency information not in place.',
      recommendation: 'Set up 5S housekeeping system; place spill kit near chemical storage; display emergency numbers + assembly point; appoint Safety Officer if >250 workers.',
      timeline: '30_days',
      penaltyExposure: 'Rs.2 lakh per default under OSH Code safety obligations',
    },
    compliantAnswers: ['yes'],
    appliesWhen: workshopOnly,
  },
]
