import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import { jsPDF } from 'jspdf'

import { APPLICABILITY_QUESTIONS } from '@/lib/assessments/auto-dealer/applicability-questions'
import { PHASE2_STATUTORY_QUESTIONS as PHASE_2_QUESTIONS } from '@/lib/assessments/auto-dealer/phase-2-statutory'
import { PHASE3_WORKSHOP_EHS_QUESTIONS as PHASE_3_QUESTIONS } from '@/lib/assessments/auto-dealer/phase-3-workshop-ehs'
import { PHASE4_DEALER_SPECIFIC_QUESTIONS as PHASE_4_QUESTIONS } from '@/lib/assessments/auto-dealer/phase-4-dealer-specific'
import { PHASE5_EPR_QUESTIONS as PHASE_5_QUESTIONS } from '@/lib/assessments/auto-dealer/phase-5-epr'
import { PHASE6_DATA_CORPORATE_QUESTIONS as PHASE_6_QUESTIONS } from '@/lib/assessments/auto-dealer/phase-6-data-corporate'
import {
  buildApplicabilityProfileFromResponses,
  computePhaseScores,
  computeOverallScore,
  generateGapAnalysis,
  generateApplicabilityChecks,
  computePriceTier,
} from '@/lib/assessments/auto-dealer/rules-engine'
import type {
  Responses, PhaseScore, OverallScore, GapItem,
  ApplicabilityCheckResult, PTSlab, StateAndE, GSTRate,
  ApplicabilityProfile,
} from '@/types/auto-dealer'
import { PHASE_METADATA, PRICE_TIERS } from '@/types/auto-dealer'

const ALL_QUESTIONS = [
  ...APPLICABILITY_QUESTIONS,
  ...PHASE_2_QUESTIONS,
  ...PHASE_3_QUESTIONS,
  ...PHASE_4_QUESTIONS,
  ...PHASE_5_QUESTIONS,
  ...PHASE_6_QUESTIONS,
]

// eslint-disable-next-line @typescript-eslint/no-explicit-any
let _supabase: any = null
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function getSupabase(): any {
  if (!_supabase) {
    _supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!
    )
  }
  return _supabase
}

// ============================================================================
// CONSTANTS
// ============================================================================

const PAGE_W = 210
const PAGE_H = 297
const ML = 15   // margin left
const MR = 15   // margin right
const MT = 15   // margin top
const MB = 20   // margin bottom
const CW = PAGE_W - ML - MR  // content width

const C = {
  primary:   [30, 64, 175]  as [number, number, number],
  success:   [34, 197, 94]  as [number, number, number],
  warning:   [245, 158, 11] as [number, number, number],
  danger:    [220, 38, 38]  as [number, number, number],
  text:      [31, 41, 55]   as [number, number, number],
  muted:     [107, 114, 128] as [number, number, number],
  lightGray: [243, 244, 246] as [number, number, number],
  white:     [255, 255, 255] as [number, number, number],
}

// ASCII-safe sanitiser
function ascii(s: string): string {
  if (!s) return ''
  return s
    .replace(/₹/g, 'Rs.')
    .replace(/[₹]/g, 'Rs.')
    .replace(/[–—]/g, '-')
    .replace(/[""]/g, '"')
    .replace(/['']/g, "'")
    .replace(/[•·•]/g, '*')
    .replace(/…/g, '...')
    .replace(/ /g, ' ')
    .replace(/→/g, '->')
    .replace(/[^\x00-\x7F]/g, '')
}

function severityColor(sev: string): [number, number, number] {
  if (sev === 'critical' || sev === 'high') return C.danger
  if (sev === 'medium') return C.warning
  return C.success
}

function statusColor(status: string): [number, number, number] {
  if (status === 'green') return C.success
  if (status === 'yellow') return C.warning
  return C.danger
}

function statusLabel(status: string): string {
  if (status === 'green') return 'GREEN'
  if (status === 'yellow') return 'YELLOW'
  return 'RED'
}

function pageBreak(doc: jsPDF, y: number, needed: number): number {
  if (y + needed > PAGE_H - MB) {
    doc.addPage()
    return MT
  }
  return y
}

function addHeader(doc: jsPDF, company: string, pageNum: number): void {
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...C.muted)
  doc.text(ascii(company), ML, 10)
  doc.text(`Page ${pageNum}`, PAGE_W - MR, 10, { align: 'right' })
}

function addFooter(doc: jsPDF): void {
  doc.setFontSize(7)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...C.muted)
  doc.text(
    'Generated by ComplianceCheck.co.in | This report does not constitute legal advice',
    ML, PAGE_H - MB + 5
  )
}

function hline(doc: jsPDF, y: number, color: [number, number, number] = C.lightGray): void {
  doc.setDrawColor(...color)
  doc.setLineWidth(0.3)
  doc.line(ML, y, PAGE_W - MR, y)
}

// --------------------------------------------------------------------------
// PDF generator (pure function — no side effects)
// --------------------------------------------------------------------------

interface ReportData {
  assessmentId: string
  email: string
  fullName: string | null
  companyName: string | null
  labourRegime: string
  profile: ApplicabilityProfile
  phaseScores: PhaseScore[]
  overallScore: OverallScore
  gapAnalysis: GapItem[]
  applicabilityChecks: ApplicabilityCheckResult[]
  totalQuestions: number
  priceTier: 'basic' | 'standard' | 'premium'
  generatedAt: string
}

function generatePdf(data: ReportData): Uint8Array {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const company = ascii(data.companyName ?? 'N/A')
  let pageNum = 1

  // ==========================================================================
  // PAGE 1 — COVER
  // ==========================================================================

  // Blue header bar
  doc.setFillColor(...C.primary)
  doc.rect(0, 0, PAGE_W, 60, 'F')
  doc.setFontSize(26)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...C.white)
  doc.text('ComplianceCheck', PAGE_W / 2, 35, { align: 'center' })
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text('Pay-as-you-go Compliance Assessments for Indian SMEs', PAGE_W / 2, 48, { align: 'center' })

  // Assessment title
  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...C.text)
  doc.text('Auto Dealership', PAGE_W / 2, 85, { align: 'center' })
  doc.text('Compliance Assessment', PAGE_W / 2, 97, { align: 'center' })

  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...C.muted)
  doc.text('Full Compliance Report — All Phases', PAGE_W / 2, 108, { align: 'center' })

  // "Prepared For" box
  doc.setFillColor(...C.lightGray)
  doc.rect(ML, 118, CW, 52, 'F')

  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...C.muted)
  doc.text('Prepared For', ML + 5, 126)

  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...C.text)
  doc.text(company, ML + 5, 135)

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...C.muted)
  doc.text(ascii(data.fullName ?? 'N/A'), ML + 5, 143)
  doc.text(ascii(data.email), ML + 5, 150)
  doc.text(
    `Labour Regime: ${data.labourRegime === 'new' ? 'New Labour Codes (eff. 21 Nov 2025)' : 'Legacy Acts'}`,
    ML + 5, 157
  )
  doc.text(`Price Tier: ${ascii(PRICE_TIERS.find(t => t.id === data.priceTier)?.label ?? data.priceTier)}`, ML + 5, 164)

  // Assessment date
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...C.text)
  doc.text(`Assessment Date: ${ascii(data.generatedAt)}`, ML, 185)
  doc.text(`Assessment ID: ${data.assessmentId.slice(0, 8)}`, ML, 192)

  // Overall score hero
  const sc = data.overallScore
  const scColor = statusColor(sc.status)
  doc.setFontSize(42)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...scColor)
  doc.text(`${sc.score}`, ML, 220)
  doc.setFontSize(20)
  doc.text('/100', ML + 28, 220)

  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...C.text)
  doc.text('Overall Compliance Score', ML, 228)

  doc.setFontSize(10)
  doc.setTextColor(...scColor)
  doc.setFont('helvetica', 'bold')
  doc.text(
    sc.status === 'green' ? 'GREEN — Strong' : sc.status === 'yellow' ? 'YELLOW — Moderate' : 'RED — Material Gaps',
    ML, 235
  )

  // Confidential footer on cover
  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...C.danger)
  doc.text('CONFIDENTIAL — For Internal Use Only', PAGE_W / 2, PAGE_H - 10, { align: 'center' })

  // ==========================================================================
  // PAGE 2 — EXECUTIVE SUMMARY
  // ==========================================================================

  doc.addPage()
  pageNum++
  addHeader(doc, company, pageNum)
  addFooter(doc)

  let y = 20

  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...C.primary)
  doc.text('Executive Summary', ML, y)
  y += 12

  // Score + status boxes side by side
  const bw = (CW - 5) / 2
  doc.setFillColor(...statusColor(sc.status))
  doc.rect(ML, y, bw, 28, 'F')
  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...C.white)
  doc.text('Overall Score', ML + 3, y + 6)
  doc.setFontSize(22)
  doc.text(`${sc.score}/100`, ML + 3, y + 20)

  const riskText = sc.status === 'green' ? 'Low Risk' : sc.status === 'yellow' ? 'Moderate Risk' : 'High Risk'
  doc.setFillColor(...(sc.status === 'green' ? C.success : sc.status === 'yellow' ? C.warning : C.danger))
  doc.rect(ML + bw + 5, y, bw, 28, 'F')
  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...C.white)
  doc.text('Risk Level', ML + bw + 8, y + 6)
  doc.setFontSize(14)
  doc.text(riskText, ML + bw + 8, y + 20)
  y += 36

  // Key stats row
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...C.text)
  doc.text(`Points Earned: ${sc.totalEarned} of ${sc.totalMax}`, ML, y)
  doc.text(`Questions Answered: ${data.totalQuestions}`, ML + 80, y)
  y += 10

  hline(doc, y)
  y += 6

  // Phase scores table
  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...C.primary)
  doc.text('Phase-by-Phase Breakdown', ML, y)
  y += 8

  // Table header
  doc.setFillColor(...C.primary)
  doc.rect(ML, y, CW, 7, 'F')
  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...C.white)
  doc.text('Phase', ML + 2, y + 5)
  doc.text('Score', ML + 88, y + 5)
  doc.text('Compliant', ML + 112, y + 5)
  doc.text('Status', ML + 148, y + 5)
  y += 9

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  for (const ps of data.phaseScores) {
    y = pageBreak(doc, y, 8)
    const info = PHASE_METADATA.find(m => m.phase === ps.phase)
    const phaseName = ascii(`Ph ${ps.phase}: ${info?.name ?? ps.phaseName}`)
    const sc2 = statusColor(ps.status)

    // Alternate row shading
    if (data.phaseScores.indexOf(ps) % 2 === 0) {
      doc.setFillColor(...C.lightGray)
      doc.rect(ML, y - 4, CW, 8, 'F')
    }

    doc.setTextColor(...C.text)
    const nameLines = doc.splitTextToSize(phaseName, 82)
    doc.text(nameLines, ML + 2, y)
    doc.text(`${ps.score}%`, ML + 88, y)
    doc.text(`${ps.compliantCount}/${ps.questionCount}`, ML + 112, y)

    // Colored status badge
    doc.setFillColor(...sc2)
    doc.rect(ML + 145, y - 3.5, 22, 5.5, 'F')
    doc.setFontSize(7)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...C.white)
    doc.text(statusLabel(ps.status), ML + 147, y)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.setTextColor(...C.text)

    y += nameLines.length > 1 ? nameLines.length * 4 + 2 : 8
  }
  y += 4
  hline(doc, y)
  y += 8

  // High-level gap summary
  const highGaps = data.gapAnalysis.filter(g => g.severity === 'critical' || g.severity === 'high').length
  const medGaps  = data.gapAnalysis.filter(g => g.severity === 'medium').length
  const lowGaps  = data.gapAnalysis.filter(g => g.severity === 'low').length
  const compliantCount = data.applicabilityChecks.filter(c => c.applies).length

  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...C.primary)
  doc.text('Key Findings', ML, y)
  y += 8

  const findings = [
    `* ${data.gapAnalysis.length} compliance gap(s) identified across all phases`,
    `* ${highGaps} Critical/High priority items requiring immediate action`,
    `* ${medGaps} Medium priority items — address within 30-60 days`,
    `* ${lowGaps} Low priority items — address as resources permit`,
    `* ${compliantCount} applicable regulatory obligations identified`,
  ]
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(...C.text)
  for (const f of findings) {
    y = pageBreak(doc, y, 6)
    doc.text(ascii(f), ML + 3, y)
    y += 6
  }

  // ==========================================================================
  // PAGE 3+ — APPLICABILITY OVERVIEW
  // ==========================================================================

  doc.addPage()
  pageNum++
  addHeader(doc, company, pageNum)
  addFooter(doc)
  y = 20

  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...C.primary)
  doc.text('Applicability Overview', ML, y)
  y += 6

  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...C.muted)
  doc.text('Regulatory obligations checked against your dealership profile.', ML, y)
  y += 10

  // Group by phase
  const byPhase: Record<number, typeof data.applicabilityChecks> = {}
  for (const ch of data.applicabilityChecks) {
    if (!byPhase[ch.phase]) byPhase[ch.phase] = []
    byPhase[ch.phase].push(ch)
  }

  for (const phaseKey of Object.keys(byPhase).map(Number).sort()) {
    const checks = byPhase[phaseKey]
    const info = PHASE_METADATA.find(m => m.phase === phaseKey)
    y = pageBreak(doc, y, 12)

    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...C.text)
    doc.text(ascii(`Phase ${phaseKey}: ${info?.name ?? ''}`), ML, y)
    y += 7

    for (const ch of checks) {
      y = pageBreak(doc, y, 6)
      const badge = ch.applies ? '[Y]' : '[N]'
      const badgeColor = ch.applies ? C.success : C.muted

      doc.setFontSize(8)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...badgeColor)
      doc.text(badge, ML + 2, y)

      doc.setFont('helvetica', 'normal')
      doc.setTextColor(...C.text)
      const labelLines = doc.splitTextToSize(ascii(ch.label), CW - 20)
      doc.text(labelLines, ML + 12, y)
      y += labelLines.length * 4

      doc.setTextColor(...C.muted)
      const reasonLines = doc.splitTextToSize(ascii(ch.triggerReason), CW - 20)
      doc.text(reasonLines, ML + 12, y)
      y += reasonLines.length * 3.5 + 2
    }
    y += 3
    hline(doc, y)
    y += 5
  }

  // ==========================================================================
  // GAP ANALYSIS PAGES (sorted: critical → high → medium → low)
  // ==========================================================================

  const sortOrder = { critical: 0, high: 1, medium: 2, low: 3 }
  const sortedGaps = [...data.gapAnalysis].sort(
    (a, b) => (sortOrder[a.severity] ?? 3) - (sortOrder[b.severity] ?? 3)
  )

  if (sortedGaps.length > 0) {
    doc.addPage()
    pageNum++
    addHeader(doc, company, pageNum)
    addFooter(doc)
    y = 20

    doc.setFontSize(16)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...C.primary)
    doc.text('Gap Analysis', ML, y)
    y += 6

    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...C.muted)
    doc.text(`${sortedGaps.length} compliance gap(s) identified — sorted by severity.`, ML, y)
    y += 10

    let n = 1
    for (const gap of sortedGaps) {
      const needed = 45
      if (y + needed > PAGE_H - MB) {
        doc.addPage()
        pageNum++
        addHeader(doc, company, pageNum)
        addFooter(doc)
        y = 20
      }

      const sevColor = severityColor(gap.severity)

      // Severity badge
      const badgeW = 22
      doc.setFillColor(...sevColor)
      doc.rect(ML, y, badgeW, 6, 'F')
      doc.setFontSize(7)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...C.white)
      doc.text(gap.severity.toUpperCase(), ML + 2, y + 4.5)

      // Phase tag
      doc.setFontSize(8)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(...C.muted)
      const info2 = PHASE_METADATA.find(m => m.phase === gap.phase)
      doc.text(ascii(`Phase ${gap.phase}: ${info2?.name ?? gap.phaseName}`), ML + badgeW + 3, y + 4.5)
      y += 9

      // Title
      doc.setFontSize(10)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...C.text)
      const titleLines = doc.splitTextToSize(ascii(`${n}. ${gap.title}`), CW - 4)
      doc.text(titleLines, ML + 2, y)
      y += titleLines.length * 5 + 2

      // Finding
      doc.setFontSize(8)
      doc.setFont('helvetica', 'italic')
      doc.setTextColor(...C.muted)
      const findLines = doc.splitTextToSize(ascii(gap.finding), CW - 4)
      doc.text(findLines, ML + 2, y)
      y += findLines.length * 4 + 2

      // Recommendation
      doc.setFontSize(9)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...C.text)
      doc.text('Recommendation:', ML + 2, y)
      y += 5
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(9)
      const recLines = doc.splitTextToSize(ascii(gap.recommendation), CW - 6)
      doc.text(recLines, ML + 4, y)
      y += recLines.length * 4 + 2

      // Timeline + Penalty row
      doc.setFontSize(8)
      doc.setTextColor(...C.muted)
      doc.text(`Timeline: ${ascii(gap.timeline.replace(/_/g, ' '))}`, ML + 2, y)

      if (gap.penaltyExposure) {
        doc.setFont('helvetica', 'bold')
        doc.setTextColor(...C.danger)
        const penText = `Penalty: ${ascii(gap.penaltyExposure)}`
        const penLines = doc.splitTextToSize(penText, CW / 2 - 4)
        doc.text(penLines, ML + 90, y)
        doc.setFont('helvetica', 'normal')
        doc.setTextColor(...C.muted)
      }
      y += 5

      // Source
      doc.setFontSize(7)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(...C.muted)
      doc.text(`Source: ${ascii(gap.source)}`, ML + 2, y)
      y += 4

      hline(doc, y)
      y += 5
      n++
    }
  } else {
    doc.addPage()
    pageNum++
    addHeader(doc, company, pageNum)
    addFooter(doc)
    y = 20

    doc.setFontSize(16)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...C.success)
    doc.text('No Compliance Gaps Identified', ML, y)
    y += 10
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...C.text)
    doc.text('Your dealership is fully compliant across all assessed phases.', ML, y)
  }

  // ==========================================================================
  // NEXT STEPS & RESOURCES PAGE
  // ==========================================================================

  doc.addPage()
  pageNum++
  addHeader(doc, company, pageNum)
  addFooter(doc)
  y = 20

  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...C.primary)
  doc.text('Next Steps & Resources', ML, y)
  y += 12

  // Recommended timeline
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...C.text)
  doc.text('Recommended Action Timeline', ML, y)
  y += 8

  doc.setFillColor(...C.primary)
  doc.rect(ML, y, CW, 7, 'F')
  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...C.white)
  doc.text('Timeframe', ML + 2, y + 5)
  doc.text('Action', ML + 60, y + 5)
  y += 9

  const timeline = [
    ['Immediate',           'Address CRITICAL and HIGH severity gaps'],
    ['30-60 days',          'Resolve MEDIUM severity gaps and register pending licences'],
    ['3-6 months',          'Complete LOW severity items and staff training'],
    ['Annual',              'Re-assessment and compliance calendar review'],
  ]
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(...C.text)
  for (let i = 0; i < timeline.length; i++) {
    if (i % 2 === 0) {
      doc.setFillColor(...C.lightGray)
      doc.rect(ML, y - 3.5, CW, 7, 'F')
    }
    doc.text(ascii(timeline[i][0]), ML + 2, y)
    const tLines = doc.splitTextToSize(ascii(timeline[i][1]), CW - 64)
    doc.text(tLines, ML + 60, y)
    y += tLines.length * 4 + 3
  }
  y += 5
  hline(doc, y)
  y += 8

  // Government resources
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...C.primary)
  doc.text('Government Resources', ML, y)
  y += 8

  const resources = [
    ['Ministry of Road Transport & Highways (MoRTH)', 'morth.gov.in'],
    ['Central Motor Vehicles Rules — HSRP', 'parivahan.gov.in'],
    ['Bureau of Indian Standards (BIS) — CMVR', 'bis.gov.in'],
    ['IRDAI — Insurance Regulatory Guidelines',  'irdai.gov.in'],
    ['RBI — DSA / Vehicle Finance Norms',        'rbi.org.in'],
    ['CPCB — EPR / Waste Management Rules',      'cpcb.nic.in'],
    ['MCA — Companies Act / CSR',                'mca.gov.in'],
    ['MeitY — DPDP Act 2023',                    'meity.gov.in'],
  ]
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  for (const [name, url] of resources) {
    y = pageBreak(doc, y, 7)
    doc.setTextColor(...C.text)
    doc.setFont('helvetica', 'bold')
    doc.text(ascii(name), ML + 2, y)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...C.primary)
    doc.text(url, ML + 2, y + 4.5)
    doc.setTextColor(...C.text)
    y += 11
  }
  y += 3
  hline(doc, y)
  y += 8

  // Disclaimer box
  y = pageBreak(doc, y, 28)
  doc.setFillColor(255, 237, 213)  // amber-100
  doc.rect(ML, y, CW, 22, 'F')
  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(180, 83, 9)  // amber-700
  doc.text('DISCLAIMER', ML + 3, y + 6)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(...C.text)
  const disc = 'This report provides general guidance based on central legislation and research current to May 2026. ' +
    'State-specific rules vary and change with Budgets. DPDP Act 2023 substantive obligations take effect 13 May 2027 — ' +
    'items marked "Prepare by 2027" are advisory. Always consult a qualified compliance professional for legal advice.'
  const discLines = doc.splitTextToSize(ascii(disc), CW - 6)
  doc.text(discLines, ML + 3, y + 11)
  y += 24

  // Report metadata
  doc.setFontSize(7)
  doc.setTextColor(...C.muted)
  doc.text(`Report Generated: ${ascii(data.generatedAt)}`, ML, y)
  doc.text(`Assessment ID: ${data.assessmentId.slice(0, 8)}`, ML, y + 4)

  return doc.output('arraybuffer') as unknown as Uint8Array
}

// --------------------------------------------------------------------------
// Route handler
// --------------------------------------------------------------------------

export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  const assessmentId = params.id
  const acceptJson = request.headers.get('accept')?.includes('application/json')

  try {
    const supabase = getSupabase()

    const { data: row, error: fetchErr } = await supabase
      .from('auto_dealer_assessments')
      .select('*')
      .eq('id', assessmentId)
      .single()

    if (fetchErr || !row) {
      return NextResponse.json({ error: 'Assessment not found' }, { status: 404 })
    }

    const a = row as {
      id: string; user_email: string; email_verified: boolean;
      full_name: string | null; company_name: string | null; phone: string | null;
      responses: Responses; applicability_profile: ApplicabilityProfile | null;
      phase_scores: PhaseScore[] | null; gap_analysis: GapItem[] | null;
      overall_score: number | null; compliance_status: string | null;
      payment_status: string; price_tier: string | null;
      labour_regime: string; created_at: string;
    }

    // Always recompute scores from stored responses to avoid stale cached values
    const responses: Responses = (a.responses as Responses) ?? {}
    const profile = buildApplicabilityProfileFromResponses(responses)
    const phaseScores: PhaseScore[] = computePhaseScores(profile, ALL_QUESTIONS, responses)
    const overallScore: OverallScore = computeOverallScore(phaseScores)
    const gapAnalysis: GapItem[] = generateGapAnalysis(profile, ALL_QUESTIONS, responses)
    const applicabilityChecks: ApplicabilityCheckResult[] = generateApplicabilityChecks(profile)
    const tier = (a.price_tier ?? computePriceTier(profile, ALL_QUESTIONS)) as 'basic' | 'standard' | 'premium'
    const totalQuestions = ALL_QUESTIONS.filter(q => q.phase !== 1 && q.appliesWhen(profile)).length

    // Fetch state reference data for verified + paid users
    let ptSlabs: PTSlab[] = []
    let sandE: StateAndE[] = []
    let gstRates: GSTRate[] = []

    if (a.email_verified && a.payment_status === 'paid') {
      const [ptResult, sandEResult, gstResult] = await Promise.all([
        supabase.from('state_pt_slabs').select('*').in('state_code', profile.statesOfOperation),
        supabase.from('state_s_and_e').select('*').in('state_code', profile.statesOfOperation),
        supabase.from('gst_rates_by_hsn').select('*').order('hsn'),
      ])
      if (ptResult.data) ptSlabs = ptResult.data as PTSlab[]
      if (sandEResult.data) sandE = sandEResult.data as StateAndE[]
      if (gstResult.data) gstRates = gstResult.data as GSTRate[]
    }

    // Require email verification for both JSON and PDF responses
    if (!a.email_verified) {
      return NextResponse.json({ error: 'Email verification required' }, { status: 403 })
    }

    // JSON response for the results page metadata fetch
    if (acceptJson) {
      return NextResponse.json({
        email: a.user_email,
        companyName: a.company_name,
        fullName: a.full_name,
        labourRegime: a.labour_regime,
        responses,
        phaseScores,
        overallScore,
        gapAnalysis,
        applicabilityChecks,
        profile,
        ptSlabs,
        sandE,
        gstRates,
        emailVerified: a.email_verified,
        paymentStatus: a.payment_status,
        priceTier: tier,
        totalQuestions,
      })
    }

    const pdfData = generatePdf({
      assessmentId,
      email: a.user_email,
      fullName: a.full_name,
      companyName: a.company_name,
      labourRegime: a.labour_regime,
      profile,
      phaseScores,
      overallScore,
      gapAnalysis,
      applicabilityChecks,
      totalQuestions,
      priceTier: tier,
      generatedAt: new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' }),
    })

    // Mark PDF generated
    await supabase
      .from('auto_dealer_assessments')
      .update({ pdf_generated_at: new Date().toISOString() })
      .eq('id', assessmentId)

    return new NextResponse(Buffer.from(pdfData), {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="compliance-report-${assessmentId.slice(0, 8)}.pdf"`,
        'Cache-Control': 'private, no-cache',
      },
    })
  } catch (err) {
    console.error('Report route error:', err)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
